### ISSUE TITLE
the ENV["PYTHON"]="path/to/python.exe" not work for python3.12.0

### ISSUE THREAD

**Issue by nil-is-lin** [JuliaPy/PyCall.jl#1060]
I have upgrade the python to python 3.12.0. However, it can't find the package "matplotlib" install by pip, which works well for the old version of python(3.11.3).  It should be the problem for new python version, I guess.

there is no error in the process "set ENV, build PyCall". It just cant change to the system-wide python.

**Comment by stevengj** [comment]
Can you show *exactly* what you did? 

You should 
1. Start a fresh Julia session
2. Set your `ENV["PYTHON"]` appropriately
3. run `using PyCall` and check that `PyCall.python` is the desired python
4. try `pyimport("matplotlib")` and see whether it succeeds

**Comment by nil-is-lin** [comment]
I believe the following screenshot can illustrate my problem.
![image](https://github.com/JuliaPy/PyCall.jl/assets/6971475/a4f42e55-2282-4861-8f57-7a05e57bef97)

> julia> using PyCall
> 
> julia> PyCall.python
> "C:\\Users\\nil_l\\.julia\\conda\\3\\x86_64\\python.exe"
> 
> julia> ENV["PYTHON"]
> "D:\\Python\\Python312\\python.exe"
> 
> (@v1.9) pkg> build PyCall
>     Building Conda ─→ `C:\Users\nil_l\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\8c86e48c0db1564a1d49548d3515ced5d604c408\build.log`
>     Building PyCall → `C:\Users\nil_l\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\43d304ac6f0354755f1d60730ece8c499980f7ba\build.log`
> 
> julia> PyCall.python
> "C:\\Users\\nil_l\\.julia\\conda\\3\\x86_64\\python.exe"

**Comment by stevengj** [comment]
You need to start a new session after building PyCall.

**Comment by nil-is-lin** [comment]
You are right. I used the wrong process, every time I used PyCall to see if it changed, and then built again, so it didn't work.
