### ISSUE TITLE
PyCall 1.96.2 breaks tests at Imbalance.jl

### ISSUE THREAD

**Issue by ablaom** [JuliaPy/PyCall.jl#1064]
I can reproduce the following CI fail on my mac under Julia 1.9.1 and julia 1.6.5 (errors are slightly different):

https://github.com/JuliaAI/Imbalance.jl/actions/runs/6949846973/job/18908791611

However, if I pin PyCall to 1.96.1 then tests pass locally on my machine.

**Comment by ablaom** [comment]
(PyCall is only a test dependency of Imbalance.jl)

**Comment by stevengj** [comment]
Nowadays you need to put version numbers for your stdlibs, and it looks like PyCall doing so broke your package:

https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958

Maybe update your Project.toml with the new recommended compat entries?

**Comment by ablaom** [comment]
Thanks @stevengj .  The strange thing is that that some standard libraries that appear in the error messages (which ones appear to change depending on Julia version) are not even used in the package or in tests. So, for example, `Libdl` and `Dates`.

@EssamWisam Do you want to see if adding compats for our stdlibs makes any difference? I think they are just Statistics, Random, and LinearAlgebra.

**Comment by EssamWisam** [comment]
> @EssamWisam Do you want to see if adding compats for our stdlibs makes any difference? I think they are just Statistics, Random, and LinearAlgebra.

Will try. I suppose I should be using the most recent versions.

**Comment by ablaom** [comment]
Yeah, in even in Julia 1.9.1 some libraries (e.g, Random) don't even show a version number.
