### ISSUE TITLE
Do you have plan to add exec?

### ISSUE THREAD

**Issue by colinfang** [JuliaPy/PyCall.jl#255]
`eval` only evaluate expressions.

Is it possible to have `exec` as well so we can define python functions in julia.

**Comment by stevengj** [comment]
I've thought about it.  It would be nice to define a custom string macro, too, so that you could do:
```
py"""
....Python code goes here...
"""
```
to evaluate Python code.

Ideally it would work like evaluating an IPython notebook cell -- i.e. it would return the result of the last expression evaluated.  Would love to see someone take a crack at this.

**Comment by novatena2015** [comment]
With the below macro any python code can be executed from julia. But I don't know how to get the result of the last expression.
```
macro py_str(ex)
       pybuiltin("eval")(pybuiltin("compile")(ex,"<string>","exec"),Dict())
end
```

For example:

py"""
def myfunc(x):
    return x*x
x = 5
print(myfunc(x))
"""
will print 25 but returns Void to julia

**Comment by stevengj** [comment]
@Carreau, how does IPython evaluate code cells so that it (a) gets the value of the last expression and (b) defines variables in the global scope?

**Comment by Carreau** [comment]
We manually [get the ast](https://github.com/ipython/ipython/blob/54d60477b4c420bd6a1279a5569b5f1ffcd94d9f/IPython/core/interactiveshell.py#L2690) and [run each runnable bloc independently](https://github.com/ipython/ipython/blob/54d60477b4c420bd6a1279a5569b5f1ffcd94d9f/IPython/core/interactiveshell.py#L2817-L2828), Python provide natively an [`exec`](https://docs.python.org/3/library/functions.html#exec) that takes a namespace for both globals and the user one , we just the [use it](https://github.com/ipython/ipython/blob/54d60477b4c420bd6a1279a5569b5f1ffcd94d9f/IPython/core/interactiveshell.py#L2881). So technically we are not evaluating in the global scope, but in a subscope (which appears as the main one for the user but has a few [escape hatches](https://github.com/ipython/ipython/blob/54d60477b4c420bd6a1279a5569b5f1ffcd94d9f/IPython/core/interactiveshell.py#L1150-L1208)). Does that helps ?

**Comment by stevengj** [comment]
Thanks @Carreau!

**Comment by stevengj** [comment]
Multi-line input via `py"""...."""` is now supported, ala `exec`, so I'm closing this issue. 

It would be nice to be able to return the result of the last expression, similar to Python, and I opened a new issue #348 for that.
