### ISSUE TITLE
make arbitrary Julia objects callable in Python

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/PyCall.jl#319]
See JuliaInterop/pyjulia#63 ... right now, PyCall only adds a call slot when translating Julia functions, but nowadays any arbitrary Julia object may be callable.

**Comment by jingpengwu** [comment]
this feature is pretty useful, any update?

**Comment by stevengj** [comment]
No update at the moment; a PR would be welcome.

**Comment by jingpengwu** [comment]
It seems that solving such a problem needs a deep understanding of the underlying data structure of both python and julia objects? I don't think I have such knowledge yet, but would like to have a try. @stevengj Would you like to give a clue of how to do it?

**Comment by stevengj** [comment]
Look at the source code for `callback.jl` in PyCall.   That basically just needs to be merged in to `pytype.jl` so that it applies to all `jlwrap` objects and not just functions.

**Comment by Keno** [comment]
Now fixed
