### ISSUE TITLE
Subclasses of dict, array, etc... lose custom methods

### ISSUE THREAD

**Issue by marius311** [JuliaPy/PyCall.jl#323]
If I have a Python subclass of e.g. `dict`

```python
class mydict(dict):
   def myfunc():
      # do stuff...
```

When I load an object of this type in Julia using PyCall, it's converted to a Julia Dict and hence looses `myfunc`. Same thing happens with all the objects which are automatically converted. Is there any way around this?

**Comment by stevengj** [comment]
Use `foo["bar"]` instead of `foo[:bar]` to avoid the automatic conversion when accessing members.   In a function call, you can use `pycall(myfunc, PyObject, args...)` to avoid automatic conversion of the result.

**Comment by marius311** [comment]
Ah yes that did it (and I see now I missed that this is documented in the main readme).Thanks for the quick reply!
