### ISSUE TITLE
using pynauty module in Julia 

### ISSUE THREAD

**Issue by husemoller90** [JuliaPy/PyCall.jl#335]
I would like to find the automorphism group of a (bipartite) graph (it is an object created using the LightGraphs package), and to do this I would like to call pynauty in Julia. 

I followed PyCall documentation and I can import pynauty executing the following lines:

`ENV["PYTHON"] = "/usr/local/bin/python"
Pkg.build("PyCall")
using PyCall
unshift!(PyVector(pyimport("sys")["path"]), "")
@pyimport pynauty`

Now, I am able to define a pynauty Graph object as:
`g = pynauty.Graph(5)`
which create an empty Graph with 5 vertices, however, if I try to add edges to g via 
`g[:connect_vertex](0, [1,2,3])`
I get the following error: 

`ERROR: PyError (:PyObject_Call) <type 'exceptions.ValueError'> ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',) File "/Users/---/Library/Python/2.7/lib/python/site-packages/py‌​nauty/graph.py", line 108, in connect_vertex self._check_vertices([neighbors]) File "/Users/---/Library/Python/2.7/lib/python/site-packages/py‌​nauty/graph.py", line 68, in _check_vertices if not (0 <= v and v < self.number_of_vertices):`

Could it be that a Julia array is misintepreted? Or is it a bug of PyCall?

**Comment by cstjean** [comment]
From its docstring it looks like `connect_vertex` is expecting a Python list, but `g[:connect_vertex](0, [1,2,3])` will automatically turn the Julia vector `[1,2,3]` into a numpy array. I believe that `g[:connect_vertex](0, PyCall.array2py([1,2,3]))` should work.

**Comment by husemoller90** [comment]
Thank you very much for your prompt reply. Your suggestion works indeed! 
All the best.

**Comment by stevengj** [comment]
`Any[1,2,3]` will also convert to a Python list.
