### ISSUE TITLE
Tag a new release to avoid some deprecation warnings

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPy/PyCall.jl#337]
These deprecation warnings in the released PyCall seem to be fixed on master. Would be great to tag a new release.

![](https://cloud.githubusercontent.com/assets/25916/21452196/466f5ef0-c92b-11e6-9809-fdf7f302cb32.png)

**Comment by ViralBShah** [comment]
Cc @shashi

**Comment by stevengj** [comment]
Did you mean to file this issue with IJulia?

**Comment by ViralBShah** [comment]
Apparently when we looked into it, the warning was not in IJulia, but I can look into it once again.

**Comment by shashi** [comment]
This warning was fixed in https://github.com/JuliaPy/PyCall.jl/commit/66bcf2f8e57942576f385463d5248f0035764527

**Comment by stevengj** [comment]
Oh, right.  Sorry, I thought we tagged this ages ago.
