### ISSUE TITLE
Trouble instantiating class

### ISSUE THREAD

**Issue by TsurHerman** [JuliaPy/PyCall.jl#339]
I am trying to access an IR camera in julia through a python package that wraps a C++ driver
for that camera.

This works in Python:
```
import ids
Camera = ids.Camera() 
```

This fails in julia:
```
using PyCall
@pyimport ids
Camera = ids.Camera()
```

but not due to some error in the package ..  this is the error I am getting:
```
ERROR: PyError (:PyObject_Call) <type 'exceptions.IOError'>
IOError('Unable to open camera (Error 155).',)
  File "build\bdist.win-amd64\egg\ids.py", line 54, in __init__
    super(Camera, self).__init__(*args, **kwargs)

 in pyerr_check at C:\Users\tsurh\.julia\v0.5\PyCall\src\exception.jl:56 [inlined]
 in pyerr_check at C:\Users\tsurh\.julia\v0.5\PyCall\src\exception.jl:61 [inlined]
 in macro expansion at C:\Users\tsurh\.julia\v0.5\PyCall\src\exception.jl:81 [inlined]
 in #_pycall#62(::Array{Any,1}, ::Function, ::PyCall.PyObject) at C:\Users\tsurh\.julia\v0.5\PyCall\src\PyCall.jl:546
 in #pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at C:\Users\tsurh\.julia\v0.5\PyCall\src\PyCall.jl:568
 in #call#67(::Array{Any,1}, ::PyCall.PyObject) at C:\Users\tsurh\.julia\v0.5\PyCall\src\PyCall.jl:571
 in (::PyCall.PyObject)() at C:\Users\tsurh\.julia\v0.5\PyCall\src\PyCall.jl:571
```

Any idea on how to work around this? I tried defining a local module with a function that will instantiate the camera for me and return the inited object.. no good.

It seems there is a difference to running statements in the python interpreter from within julia to running them from the OS shell .
I am using windows at the moment.
maybe the path is different? maybe python from julia sees a different path?

**Comment by stevengj** [comment]
Are you using the same Python version in Julia as from the shell?   (Check `PyCall.python`.)

The only difference in the path is that `.` is not in the path for PyCall, which affects if you if you try to load a local module in the current directory.

**Comment by TsurHerman** [comment]
Thanks, yes the same version.

I tried to instantiate the camera directly using ccall .. it failed.
I did a sanity check of instantiating it through C++ .. succeed.
compiled the C++ code that succeeded to a dll , ccall it from julia .. fails. what?!?
@!#$$#@
Today was a hard day

Well it does not fail , just returns an un-supported mode error ... I contacted the manufacturer, still waiting for a response).

In what way calling a function in a dll from julia is different to calling it from another C++ program?
threading support maybe? MSVCRT?

**Comment by stevengj** [comment]
Since you have boiled it down to a `ccall` unrelated to PyCall, I'm closing this issue.

I would recommend asking about it on discourse.julialang.org, as I don't have any immediate ideas.  It's possible it uses a different version of MSVCRT, but that would tend to cause a linking error.   `ccalls` are allowed to spawn threads, so that shouldn't be the issue.
