### ISSUE TITLE
How to create a converter for a python type?

### ISSUE THREAD

**Issue by bluesmoon** [JuliaPy/PyCall.jl#342]
Specifically, I would like to automatically convert Python's `datetime.time` to a Julia `CompoundPeriod`. How do I go about doing this?

Thanks.

**Comment by stevengj** [comment]
Begin by writing a manual conversion routine `convert(::Type{CompoundPeriod}, o::PyObject)`.   

Once that is working, call `PyCall.pytype_mapping(pyimport("datetime")["time"], CompoundPeriod)`.

**Comment by bluesmoon** [comment]
Great, since I've been following the `convert` approach so far with a manual call to `convert`. Let me try adding the `pytype_mapping`.

**Comment by bluesmoon** [comment]
ok, this worked.  I had to use `Dates.CompoundPeriod` since for some reason `CompoundPeriod` refuses to be imported, but other than that, it works well.

**Comment by stevengj** [comment]
`CompoundPeriod` isn't exported by the `Base.Dates` module, apparently, which is why you need to qualify it (unless you do `import Base.Dates: CompoundPeriod`).

**Comment by bluesmoon** [comment]
yeah, the import didn't help either.

**Comment by manuelma** [comment]
`convert(::Type{PyAny}, o::PyObject)` has a try catch block that hides errors in, e.g., `convert(::Type{CompoundPeriod}, o::PyObject)`, so one keeps getting a PyObject. This error was hard for me to track.
