### ISSUE TITLE
UndefVarError: query not defined

### ISSUE THREAD

**Issue by bluesmoon** [JuliaPy/PyCall.jl#344]
I'm using PyCall 1.7.2 on Julia 0.4.5 with Python 3.4.3 and I keep getting this error:
```
ERROR: UndefVarError: query not defined
 in getindex at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:261
 in pysequence_query at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:729
 [inlined code] from /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:745
 in pytype_query at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:785
 in convert at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:802
```

In particular, it happens when I'm using the `pygresql` python library to communicate with Amazon RedShift, however I cannot nail down the actual line it errors on.  Specifically, the exception call stack mentions a line number in my code where I'm referencing `cursor[:description]`, but I also have `println` statements immediately after that statement which print successfully indicating that no exception was thrown.  I'm going to try narrowing it down, but just wanted to put this here in case it rings any bells.

**Comment by stevengj** [comment]
`pysequence_query` is calling `o["__array_interface__"]` in a `try-catch` block to see whether the object supports the NumPy array interface.  Maybe your Python object is overloading `o.__array_interface__` to do some kind of query, and is getting confused?

**Comment by stevengj** [comment]
A workaround might be to circumvent the whole type-detection machinery and just tell it explicitly what type you want.   e.g. you can get the raw Python object with `cursor["description"]` (note quotes instead of colon) and then convert it as needed.

**Comment by bluesmoon** [comment]
Been trying to get that working, need to change a lot of assumptions my code makes, but I'll get there.  Thanks.

**Comment by bluesmoon** [comment]
I've changed the code, and now I get a different exception that makes no sense:
```
ERROR: TypeError: non-boolean (PyCall.PyObject) used in boolean context
 [inlined code] from /home/ubuntu/.julia/v0.4/PyCall/src/exception.jl:81
 in _pycall at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:546
 in pycall at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:568
 in call at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:571
 in execute at /home/ubuntu/lib/Modules/DBI/src/drivers/pydb-common.jl:50
```

The reason it makes no sense is because line 50 of pydb-common.jl is this:
```
    cs.cursor[:execute](stmt)
```

Where `cs.cursor` is a `PyObject` and `execute` is a method on that object. I don't see any boolean context in use here.  The only boolean context in this code is further down on line 61 which is this:
```
if typeof(description) != PyObject || description[:__eq__](nothing)
```

Could the exception be reporting the wrong line number?

**Comment by stevengj** [comment]
It looks like the error is coming from something `exception.jl`, not your code, though I'm not seeing how it could cause that problem.

**Comment by bluesmoon** [comment]
I changed some unrelated code, and now the exception location has changed to this:
```
ERROR: TypeError: non-boolean (PyCall.PyObject) used in boolean context
 in getindex at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:261
 in pysequence_query at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:729
 [inlined code] from /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:745
 in pytype_query at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:785
 in convert at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:802
 in pycall at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:568
 in call at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:571
```

**Comment by bluesmoon** [comment]
And switching back to `:description` from `"description"`, I get this:
```
ERROR: UndefVarError: query not defined
 in getindex at /home/ubuntu/.julia/v0.4/PyCall/src/PyCall.jl:261
 in pysequence_query at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:729
 [inlined code] from /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:745
 in pytype_query at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:785
 in convert at /home/ubuntu/.julia/v0.4/PyCall/src/conversions.jl:802
```
So, same location, just a different error.

**Comment by bluesmoon** [comment]
The other thing I don't understand, is I have this:
```
    try
        description = cs.cursor[:description]
    catch ex
        warn("Exception $(typeof(ex)) getting cursor description:\n$ex")
    end
```

And the exception backtrace points to the `description = cs.cursor[:description]` line, but the `catch` block never runs.

**Comment by bluesmoon** [comment]
Ok, I seem to have tracked down the problem to a part of my code that was calling a method called `query` that no longer exists. I still have no idea why the stack trace points to PyCall as it should have been at a much higher level in the stack.

If anyone has any ideas, I'd love to know, but otherwise I'm closing this.
