### ISSUE TITLE
No module named bs4, but works in python 3

### ISSUE THREAD

**Issue by datnamer** [JuliaPy/PyCall.jl#346]
Hello

`pyimport("bs4")` and `@pyimport bs4 as bs` both return: 

`PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named bs4',)`

With python 3.5, win 10 64 and julia 0.5.

No issues importing from python  3. 

`ENV["PYTHON"]` points to Anaconda3\python.exe, which is the exact path of python exe that successfully imported bs4. 

Tried reinstalling and building pycall, but to no avail. Would you have any ideas on how to resolve please?

**Comment by stevengj** [comment]
Are you sure PyPlot is configured to use the same Python version?   If you type `PyCall.python` it will tell you the name of the Python executable that PyCall was configured with.

**Comment by datnamer** [comment]
Ok...it points to ".julia\\v0.5\\Conda\\deps\\usr\\python.exe" even though PyCall build info pointed to "Anaconda3\python.exe"

**Comment by datnamer** [comment]
How can I can I change the pycall python exe?

**Comment by stevengj** [comment]
As documented in the README:
```jl
ENV["PYTHON"] = "\\...insert path here...\\Anaconda3\\python3.exe"
Pkg.build("PyCall")
```
You only need to do this once.

**Comment by datnamer** [comment]
I tried that and got ` PyCall is using \Anaconda3\python.exe ` upon building pycall.

But `Pycall.python` still says `julia\\v0.5\\Conda\\deps\\usr\\python.exe`

**Comment by datnamer** [comment]
I rebuilt pycall again and it works.

**Comment by stevengj** [comment]
You have to relaunch Julia and reload PyCall after rebuilding

**Comment by datnamer** [comment]
OK that's probably what did it.
