### ISSUE TITLE
Support for __name__ in PyCall.jlwrap

### ISSUE THREAD

**Issue by Rory-Finnegan** [JuliaPy/PyCall.jl#350]
I'm trying to wrap [keras](keras.io) and it requires that custom objective functions have a `__name__` attributed.

**Comment by Rory-Finnegan** [comment]
If anyone is curious my workaround for now is:
```julia
@pydef type Metric
    __init__(self, f) = (
        self[:f] = f;
        self[:__name__] = typeof(f).name.mt.name
    )
   __call__(self, x, y) = self[:f](Tensor(x), Tensor(y)).o
end
```

**Comment by stevengj** [comment]
Related to #268, but a `__name__` attribute should be relatively easy to add.

**Comment by Rory-Finnegan** [comment]
Wow, that was fast! Thank you.
