### ISSUE TITLE
pyeval replacement

### ISSUE THREAD

**Issue by Cody-G** [JuliaPy/PyCall.jl#352]
Overall I really like the new `py"..."` and `py"""..."""` syntax.  However there's one thing that can't figure out how to do (and that I can do with `pyeval`).

Is there a way I can interpolate a Julia string (i.e. `py"$(myJuliaString)"`) and have it be understood as a symbol rather than a python string?  I understand that something like a PySymbol type is on the to-do list and it should support what I want to do.  But until then is there a workaround that I can use other than the deprecated `pyeval`?  Thanks!

**Comment by stevengj** [comment]
Can you give an example of what you are trying to do?

**Comment by stevengj** [comment]
Maybe I could implement `py"$(myJuliaString...)"`, where the `...` would indicate pasting the string into the code.

**Comment by stevengj** [comment]
Or maybe `${...}`

**Comment by stevengj** [comment]
Oh, I have an idea: just `$$....` for literal string interpolation.

**Comment by stevengj** [comment]
I've added `$$` interpolation to insert strings directly into the Python code, which should fix this issue.

**Comment by Cody-G** [comment]
Sorry for my delayed reply, and thank you!  I like your solution.  In case you're still interested in my use case:

I'm wrapping a python package with its own implementation of units and quantities.  From python one can create a quantity like this:

`30 * ms` (30 milliseconds)

...and actually this seems like the only interface to define a quantity with the package.  So to execute the same line from Julia, I would now do this:

```
unit_str = "ms"
py"30 * $$(unit_str)"
```

**Comment by stevengj** [comment]
You should be able to call the multiplication method (I forget what it is called, __mul__ or something?) of ms directly.
