### ISSUE TITLE
how to do python's 'from ... import' ?

### ISSUE THREAD

**Issue by philtomson** [JuliaPy/PyCall.jl#357]
I see something like this in a python script and I want to run it using PyCall in Julia:

> from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets

Is this possible with @pyimport?

**Comment by stevengj** [comment]
```jl
read_data_sets = pyimport("tensorflow.contrib.learn.python.learn.datasets.mnist")["read_data_sets"]
```
