### ISSUE TITLE
segfault on ccall of PyImport_ImportModule of ctypes from pyjulia

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaPy/PyCall.jl#374]
Hello all.  I have been looking into a very common segfault that occurs over on pyjulia, and I have discovered exactly where it's coming from.  (Please take a look at my pyjulia [issue](https://github.com/JuliaPy/pyjulia/issues/92) to get some context.)

When `using PyCall` is called from PyJulia for the very first time, a segfault occurs within PyCall's `__init__` function [here](https://github.com/JuliaPy/PyCall.jl/blob/master/src/pyinit.jl#L75).  I have discovered that this indeed comes from the actual `ccall` [here](https://github.com/JuliaPy/PyCall.jl/blob/master/src/PyCall.jl#L392-L393).

I have not yet been able to reproduce the error outside of pyjulia.  The error occurs _only if_ PyCall's cache has been compiled in Julia _before_ pyjulia is constructed in Python.  If one deletes `.julia/lib/v0.5/PyCall.ji` first, forcing PyCall to be recompiled when it is called from within pyjulia, then the segfault disappears.

The details of the segfault seem to differ a bit depending on the exact circumstances under which it is called, which I think suggests there is a bad pointer or something.  To see an example, please refer to this [issue](https://github.com/JuliaPy/pyjulia/issues/92).  

**Update:** I have found an (at least temporary) fix to this issue, and at the moment it seems to be due to pyjulia loading a (known-to-be) binary incompatible cache of PyCall.  If that's what's going on, this is due entirely to a bug in pyjulia.  I'll close this issue if that is confirmed.

**Comment by stevengj** [comment]
This is a problem with pyjulia's paths, not with PyCall.
