### ISSUE TITLE
Endless miniconda install loop

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaPy/PyCall.jl#379]
Hi,

the package ExcelReaders failed to precompile (Python module xlrd not imported) and instructed me to run: ENV["PYTHON"]="" and Pkg.build("PyCall").

What follows is an endless loop of:

INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...

I am running Julia 0.5.1 on a Win10 machine, the installation came bundled in JuliaPro.

**Comment by stevengj** [comment]
Does
```
import Conda
Conda.add("numpy")
```
work?  If not, it's a problem in the Conda package.

**Comment by MaximilianJHuber** [comment]
This works if I restart Julia, leave ENV["PYTHON"] as it is (miniconda), and rebuild PyCall. 
I am now switched to Anaconda and everything works.

I guess it really was not a problem of Conda... still a bit strange...

**Comment by RobertoGarciaRJ** [comment]
I did not understand how you solved this problem. Here you are in this loop too.

**Comment by pemryan** [comment]
Here I meet the same problem when try to install JuliaPro_v0.5.2.2_build-108.exe

**Comment by pemryan** [comment]
seems something wired happens in C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\Conda\src\conda.jl, around line 186:
         if is_windows()
            if VERSION >= v"0.5.0-dev+8873" # Julia PR #13780
                run(Cmd(`$installer /S /AddToPath=0 /RegisterPython=0 /D=$PREFIX`, windows_verbatim=true))
            else
                # Workaround a bug in command-line argument parsing, see
                # https://github.com/Luthaf/Conda.jl/issues/17
                if match(r" {2,}", "") != nothing
                    error("The installer will fail when the path=\"$PREFIX\" contains two consecutive spaces")
                end
                run(`$installer /S /AddToPath=0 /RegisterPython=0 $(split("/D=$PREFIX"))`)
            end
        end


I checked the install.exe downloaded, it can be installed manually.

**Comment by stevengj** [comment]
@pemryan, please report Conda issues at [Conda.jl](https://github.com/JuliaPy/Conda.jl), not in PyCall.
