### ISSUE TITLE
Serializing objects via JLD

### ISSUE THREAD

**Issue by cstjean** [JuliaPy/PyCall.jl#387]
In ScikitLearn.jl, [I'd like to save Julia objects that contain `PyObject`s](https://github.com/cstjean/ScikitLearn.jl/issues/18). It'd be cool if `JLD.save` could handle that automatically, via their [custom serialization](https://github.com/JuliaIO/JLD.jl/blob/master/doc/jld.md#custom-serialization) interface, by calling `pickle.dumps` appropriately. The main issue is how to manage the JLD dependency in the absence of conditional module loading. What do you think? Maybe I could write a JuliaPy/PyCallJLD.jl module for optional support?

**Comment by stevengj** [comment]
A separate module (depending on both PyCall and JLD) makes the most sense here, I think.

**Comment by cstjean** [comment]
Done. Would you like to [review the code](https://github.com/JuliaPy/PyCallJLD/blob/master/src/PyCallJLD.jl)?

**Comment by cstjean** [comment]
Closed by [PyCallJLD.jl](https://github.com/JuliaPy/PyCallJLD.jl)
