### ISSUE TITLE
Add support to choose python version from miniconda

### ISSUE THREAD

**Issue by GlenHertz** [JuliaPy/PyCall.jl#397]
Hi,

I would like to be able to choose the version of Python to use inside miniconda when using:

```
ENV["PYTHON"] = ""
Pkg.build("PyCall")
```

By default it uses 2.7.12.  Is there a way to pick 3.4.3?  Maybe something like:

```
ENV["PYTHON"] = v"3.4.3"
Pkg.build("PyCall")
```

**Comment by stevengj** [comment]
This seems like it should be an issue for Conda.jl, not PyCall. Can't you already configure Conda to install python3?

**Comment by stevengj** [comment]
Fixed in JuliaPy/Conda.jl#74

**Comment by GlenHertz** [comment]
Nice improvement but I don't believe I can pick python 3.4.x. Either way the right place for this issue is in Conda so keep this closed.
