### ISSUE TITLE
PyObject(nothing) changes to PyObject(NULL) in global scope

### ISSUE THREAD

**Issue by bluesmoon** [JuliaPy/PyCall.jl#406]
This is weird.  If I declare a variable like this:

```julia
PyNone = PyObject(nothing)
```

Its actual value depends on the scope in which it is declared.  If declared locally within a function, then it becomes `PyObject None`.  If declared at module level, it becomes `PyObject NULL`.

Any idea why this happens?

**Comment by stevengj** [comment]
Global `PyObject` variables turn into NULL upon precompilation.  The right way to do this is explained in the README:  https://github.com/JuliaPy/PyCall.jl#using-pycall-from-julia-modules
