### ISSUE TITLE
Transpose not working after upgrading to 0.6

### ISSUE THREAD

**Issue by LouisMagarshack** [JuliaPy/PyCall.jl#407]
Hi all,

I'm porting some code from ancient 0.4.7 to brand new 0.6 and I ran into the following issue:

```julia
transpose([PyObject(1) PyObject(2);
       PyObject(3) PyObject(4)])
```

Doesn't work anymore, it fails with error:
 `ERROR: MethodError: no method matching transpose(::PyCall.PyObject)`.

Should I implement something like `transpose(x::PyObject) = x` or is there a better solution?

**Comment by stevengj** [comment]
0.5 removed the `transpose(x) = x` fallback, and `transpose` is recursive.  There are lots of discussions about whether to keep this behavior going forward, e.g. JuliaLang/julia#21037.

For now, the right thing is to do `permutedims(A, (2,1))` when you just want to swap the dimensions and not call `transpose` recursively.
