### ISSUE TITLE
numpy version error

### ISSUE THREAD

**Issue by jianghaizhu** [JuliaPy/PyCall.jl#412]
I have numpy 1.13.1 installed and `pyimport("numpy")` gave me version 1.7.0. How do I fix this? 

Please see the details at cstjean/ScikitLearn.jl#34

**Comment by stevengj** [comment]
Probably you have multiple versions of Python installed on your system and PyCall is not using the one you think you have.

If you look at the `PyCall.python` variable it will tell you what `python` you used when you configured PyCall.  If you want to switch to a different Python, set `ENV["PYTHON"]` to the name/path of the `python` you want and re-run `Pkg.build("PyCall")` as explained in the README.

**Comment by jianghaizhu** [comment]
It looks like Julia is using the right Python, not some system provided version. 

```
julia> PyCall.python
"/Users/zhuj6/.julia/v0.6/Conda/deps/usr/bin/python"
```

**Comment by stevengj** [comment]
Do you have any PYTHON related environment variables?  Try `collect(Iterators.filter(s -> startswith(s, "PY"), keys(ENV)))`

**Comment by stevengj** [comment]
In particular, if you set your `ENV["PYTHONPATH"]`, that could mess things up.

**Comment by jianghaizhu** [comment]
You are absolutely right. the `ENV["PYTHONPATH"]` was set to something else by another script. After I unset that, it works just fine now.  Thank you so much!
