### ISSUE TITLE
from .... import *

### ISSUE THREAD

**Issue by wilsontov** [JuliaPy/PyCall.jl#415]
Hi! How can i implement this import method: ` from SimpleCV import * ` in Julia (?) 
Thank you!

**Comment by stevengj** [comment]
You can't import Python symbols directly into the Julia namespace, but you can still call them:
```jl
@pyimport SimpleCV
logo = SimpleCV.Image("simplecv")
logo[:show]()
```
etc.  See the PyCall README.

**Comment by wilsontov** [comment]
Thank youuuu!
