### ISSUE TITLE
Get rid of the distinction between `PyCall.jlwrap` and `PyCall.jl_Function`?

### ISSUE THREAD

**Issue by Keno** [JuliaPy/PyCall.jl#421]
All Julia objects are callable nowadays, so `Function` isn't really special anymore. It would be nice if if that was reflected on the python side. If we do that, is there any good reason to keep the PyCall.jlwrap/PyCall.jl_Function distinction? @stevengj thoughts?

**Comment by ihnorton** [comment]
(ref: https://github.com/JuliaPy/PyCall.jl/issues/319)

**Comment by Keno** [comment]
Well, the simple thing here is in #422, but there's of course the question of whether we want a larger reorganization.

**Comment by stevengj** [comment]
I agree, the special function type should be merged into `jlwrap`.

**Comment by Keno** [comment]
This is done.
