### ISSUE TITLE
Make PyCall default to up-to-date most secure Python; meaning python3 (possibly python2) through Conda

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPy/PyCall.jl#435]
You may not care to support python3 over python2, just consider it; distros e.g. Ubuntu are mainly using python3 now (I'm worried python2 is left behind security wise.. maybe also python3? at least feature wise in Ubuntu).

I realize python 3[.6] by default is a breaking change, so you would just update PyCall's version number and people can always override to [distro's] python2. It's unclear that you can support newest version python of 3 or 2, if not installed; except through Conda.

I'm looking into the code to make a PR:

`let py = get(ENV, "PYTHON", isfile("PYTHON") ? readchomp("PYTHON") :`

`isfile("PYTHON")` is cryptic, a way to support python on (case-insensitive) Windows?

https://docs.python.org/3.6/whatsnew/3.6.html
"secrets: PEP 506 – Adding A Secrets Module To The Standard Library.
[..]
The hashlib and ssl modules now support OpenSSL 1.1.0."

Note that there's a new RC for 2.7.14 (Ubuntu already missing out on 2.7.13 and 12?):

https://raw.githubusercontent.com/python/cpython/c707893f9cee870bba8364b3a06eb9cfa3b80e58/Misc/NEWS

shell> python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) [..]

shell> python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) [..]

Changelog for python[2] in Ubuntu is deceiving or really at 2.7.11 but some of 2.7.12 backported?:

python-defaults (2.7.11-1) unstable; urgency=medium

  * Bump version to 2.7.11.
  * Stop shipping menu files.
  * Fix some lintian warnings.

 -- Matthias Klose <doko@debian.org>  Wed, 09 Dec 2015 13:07:35 +0100

python3-defaults (3.5.1-3) unstable; urgency=medium

  * Drop build dependency on python3.4.
  * Bump standards and debhelper versions.

 -- Matthias Klose <doko@debian.org>  Mon, 21 Mar 2016 12:58:34 +0100

**Comment by PallHaraldsson** [comment]
I see, as with PyCall, Conda supports now Python 3 and 2: https://github.com/JuliaPy/Conda.jl/commit/65d2b37d8f0b3d5a83b10e397f43aec3ef48be09

Both are done through ENV variable. I'm not sure if that is the best option; if it works to use Python 2 and 3 together.

Say you have one dependant package that REQUIREs PyCall for Python 3, would if conflict with another that assumes Python 2.

If you go with Python 3 as the new default, could it be better to fork PyCall to Py2Call so both can be used at the same time?

Py2Call could be stripped down to a minimal setup code, with REQUIREing PyCall for rest of the code.

**Comment by stevengj** [comment]
On Linux, we default to `python`.  So if the OS switches over to Python 3 as its default, we will automatically switch.  In general, I would always expect the default option to be the best-supported option.

On Mac or Windows, we default to whatever Conda defaults to, so if you think Conda should use Python 3 by default then you should make this argument in Conda.jl

**Comment by PallHaraldsson** [comment]
Right, but distros are never going to default to "python3" by default (only Arch famously did that: https://wiki.archlinux.org/index.php/python ), but all by now have it *installed* by default.

Going forward I think it's better to use Python 3 by default and not only on Windows and the other on Linux (e.g. on Arch you'll get python 3 with "python").

Python 3 seems to be in a good place already, at least all(?) of the major packages, such as matplotlib, that people are wrapping now with PyCall, so now might be a good time to make that judgement call.

Already in oldest supported Ubuntu:

https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes
"We eventually intend to ship only Python 3 with the Ubuntu desktop image, not Python 2.

[..]
Python 2 will continue to be available (as the python package) for the foreseeable future. However, to best support future versions of Ubuntu you should consider porting your code to Python 3."

https://wiki.ubuntu.com/Python/3
"For both Ubuntu and Debian, we have ongoing project goals to make Python 3 the default, preferred Python version in the distros. This means:

    Python 3 will be the only Python version installed by default."

**Comment by stevengj** [comment]
I have no objection to making the build script check for `python3` if `python` is not installed on Linux.   

Once the distros actually switch over we can make it the default too.  But I don't see much point in getting ahead of the distros here.

(Note that this has nothing to do with whether Python 3 is supported.  PyCall can and does support both Python 2 and Python 3.)

**Comment by PallHaraldsson** [comment]
"Once the distros actually switch"

Actually, in Ubuntu 16.04 I see already: 

https://wiki.ubuntu.com/XenialXerus/ReleaseNotes/

"Python2 is not installed anymore by default on the server, cloud and the touch images, long live Python3!"

So at least in case of Python 3 (and 3.6 eventually, maybe not currently) it has the advantage of beeing there over needing a download with Conda.

**Comment by PallHaraldsson** [comment]
"PyCall can and does support both Python 2 and Python 3."

I know, just curious can one dependency use Python 3 and another use [PyCall's default] Python 2?

I getting second thoughts about the proposal to change the default..

Seems most libraries are Python 3 ready, but still adoption only 28.1%:

https://semaphoreci.com/blog/2016/11/11/python-versions-used-in-commercial-projects-2016-edition.html

There's even resistance to using Python 3: https://learnpythonthehardway.org/book/nopython3.html

"And strongly recommended is to use Python 2 for Click utilities [.. as] The command line in Unix traditionally is in bytes, not Unicode." (issue also for native Julia only code?):

http://click.pocoo.org/5/python3/

**Comment by stevengj** [comment]
You need to re-configure PyCall (re-run `Pkg.build`) to use a different Python.  So no, module A cannot use PyCall with python2 at the same time (or the same package build) as module B is using PyCall with python3.
