### ISSUE TITLE
Problem with Pkg.add in Windows 10

### ISSUE THREAD

**Issue by maceta69** [JuliaPy/PyCall.jl#438]
Hello,
when i run Pkg.add for PyCall in Windows 10, I get the following error. I have been able to find similar error reports via Google but so far I haven't found a solution. The solution proposed in the error report itself doesn't seem to work.

julia> Pkg.add("PyCall")
INFO: Installing PyCall v1.14.0
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").

CondaIOError: Missing write permissions in: C:\Users\maceta\.julia\v0.6\Conda\deps\usr

 You don't appear to have the necessary permissions to install packages
 into the install area 'C:\Users\maceta\.julia\v0.6\Conda\deps\usr'.
 However you can clone this environment into your home directory and
 then make changes to it.
 This may be done using the command:

 $ conda create -n my_root --clone="C:\Users\maceta\.julia\v0.6\Conda\deps\usr"

===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`'C:\Users\maceta\.julia\v0.6\Conda\deps\usr\Scripts\conda.exe' install -y numpy`,String["TEMP=C:\\Users\\maceta\\AppData\\Local\\Temp", "USERDOMAIN_ROAMINGPROFILE=honza", "FP_NO_HOST_CHECK=NO", "USERNAME=maceta", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "LOCALAPPDATA=C:\\Users\\maceta\\AppData\\Local", "HOMEPATH=\\Users\\maceta", "CommonProgramFiles=C:\\Program Files\\Common Files", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel", "ProgramData=C:\\ProgramData", "NUMBER_OF_PROCESSORS=4", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "CONDARC=C:\\Users\\maceta\\.julia\\v0.6\\Conda\\deps\\usr\\condarc-julia.yml", "LOGONSERVER=\\\\HONZA", "APPDATA=C:\\Users\\maceta\\AppData\\Roaming", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "USERPROFILE=C:\\Users\\maceta", "PSModulePath=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=honza", "OS=Windows_NT", "windir=C:\\WINDOWS", "PROCESSOR_REVISION=3c03", "SystemRoot=C:\\WINDOWS", "TMP=C:\\Users\\maceta\\AppData\\Local\\Temp", "CONDA_PREFIX=C:\\Users\\maceta\\.julia\\v0.6\\Conda\\deps\\usr", "OneDrive=C:\\Users\\maceta\\OneDrive", "PROCESSOR_LEVEL=6", "CommonProgramW6432=C:\\Program Files\\Common Files", "CONDA_DEFAULT_ENV=C:\\Users\\maceta\\.julia\\v0.6\\Conda\\deps\\usr", "=C:=C:\\Users\\maceta\\.julia\\v0.6\\PyCall\\deps", "ProgramFiles=C:\\Program Files", "ALLUSERSPROFILE=C:\\ProgramData", "Path=C:\\Users\\maceta\\AppData\\Local\\Julia-0.6.0\\bin;C:\\Users\\maceta\\AppData\\Local\\Julia-0.6.0\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Users\\maceta\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\maceta\\AppData\\Local\\atom\\bin", "SystemDrive=C:", "HOMEDRIVE=C:", "COMPUTERNAME=HONZA", "OPENBLAS_MAIN_FREE=1", "PROCESSOR_ARCHITECTURE=AMD64", "ProgramFiles(x86)=C:\\Program Files (x86)"]), ProcessExited(1)) [1]
while loading C:\Users\maceta\.julia\v0.6\PyCall\deps\build.jl, in expression starting on line 258

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in C:\Users\maceta\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

**Comment by PallHaraldsson** [comment]
"You don't appear to have the necessary permissions" seems just like a Windows permission problem, not specific to this software.

I don't know too much about this situation, but the error message has a workaround, but you should really check your permissions/who-you're-logged-in-as?

**Comment by stevengj** [comment]
The error actually occurs with installing the Conda.jl package, not PyCall, so it would normally be reported at that package.

However, as @PallHaraldsson points out, it looks like your problem is that somehow(??) you've installed Julia's packages into a directory that you don't have write access to.  Change the directory permissions and you should be fine.  If this isn't clear, try asking on https://discourse.julialang.org/ ...

**Comment by maceta69** [comment]
Sorry, but you were not helpful at all, could at least try asking before closing the issue...
1. Changing directory perms doesn't help. First thing I tried before posting here. Also, other packages install just fine.
2. If this was a Conda issue, this package itself would not install alone. But Conda does install alone with no problems.

**Comment by stevengj** [comment]
You can install the Conda package without installing miniconda distribution.   The problem above is only getting triggered by Conda trying to install packages.  Try:
```jl
using Conda
Conda.add("numpy")
```
