### ISSUE TITLE
Bounds error when accessing PyObject with false as attributes

### ISSUE THREAD

**Issue by Escapingbug** [JuliaPy/PyCall.jl#440]
Consider flowing python code:
```
class ABC:
    def __init__(self):
        self.false = 1
```
There is some conflicts when dealing with indexing like `[:false]`, it clearly translated to `[0]`, but it is not right under this situation.

How about fixing this problem by translating `self[:False]` to `self.false` under this situation?

**Comment by yuyichao** [comment]
Doing translation like this will be a really bad idea. Juse `Symbol("false")` instead. (you can assign it to a const global in your code to save some typing.)
