### ISSUE TITLE
PyObject get is hard codded to `PyObject_GetItem`

### ISSUE THREAD

**Issue by mloubout** [JuliaPy/PyCall.jl#442]
The `get` function that allows to access a python object without copy is hard-coded to `PyObject_GetItem`.

This method fails to access any non-item such has properties that reuquire to call `PyObject_GetAttr` instead, cf https://docs.python.org/3/c-api/object.html

**Comment by stevengj** [comment]
You use `getindex` for `GetAttr`.

In particular, `o.a` in Python is equivalent to `o[:a]` or `o["a"]` in Julia.  `o[a]` is equivalent to `get(o, a)` in Julia.

I'd rater have `o[a]` in Python turn into `o[a]` in Julia, of course, but that leaves me with no nice syntax for `o.a` until Julia supports dot overloading (JuliaLang/julia#1974)

**Comment by mloubout** [comment]
>o.a in Python is equivalent to o[:a] or o["a"] in Julia.

yes, but `o.a` in python doesn't care if it is an attribute or an item, and neither is `o[:a]` in julia, the `get` function is then misleading as you can call `o[:a]` on either an item or an attribute but `get` only consider `items`.

e.g

```
class names(Object):
    __init__(self, name):
        self.name = name

    @property
    def initial(self):
        return name[0]
```

then consider the following: 

```
myname = names('mathias')
myname.inital # m, property
myname.name # mathias, item
```

will return `m`, and calling `myname[:initial]` would also in julia, but `get(myname, initial)` will fail while with the exact same syntax `myname[:name]` and `get(myname, name)` would work fine

**Comment by stevengj** [comment]
That's because you're not supposed to use `get` where you would have used `.` in Python.  You're only supposed to use `get` where you would have used `[...]` in Python.
