### ISSUE TITLE
Why always installing miniconda when conda is already installed?

### ISSUE THREAD

**Issue by Crsedf** [JuliaPy/PyCall.jl#445]
![asdasd](https://user-images.githubusercontent.com/33313012/32317618-49977fe8-bfef-11e7-85ef-218626632a68.PNG)
 It keeps going 

using Julia 0.6.1

**Comment by stevengj** [comment]
Sounds like this is a Conda issue, and should be reported at Conda.jl.  To reproduce with Conda alone, do
```
using Conda
Conda.add("numpy")
```
