### ISSUE TITLE
Error when importing Scipy

### ISSUE THREAD

**Issue by nkeito** [JuliaPy/PyCall.jl#447]
I have installed Anaconda and julia, currently I can do the following

@pyimport numpy.random as nr
nr.rand(3,4)

But when I try to do 
@pyimport scipy.optimize as so

I get:

ERROR: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package scipy.optimize could not be found by pyimport. Usually this means
that you did not install scipy.optimize in the Python version being used by PyCall...

But I already have installed scipy (in my anaconda distribution), so following the error message

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the scipy.optimize module, you can
use `pyimport_conda("scipy.optimize", PKG)`, where PKG is the Anaconda
package the contains the module scipy.optimize, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera

I did 
pyimport_conda("scipy","/Users/Angel/anaconda/lib/python2.7")
(which is the directory where scipy module is installed), but again I get the error

PackageNotFoundError: Packages missing in current channels:
            
  - /users/angel/anaconda/lib/python2.7

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://conda.anaconda.org/anaconda-fusion/osx-64
  - https://conda.anaconda.org/anaconda-fusion/noarch

So my question is what's what I'm doing wrong?

**Comment by stevengj** [comment]
PyCall is not configured to use your Anaconda Python distribution.  According to the message, it is using its own Anaconda installation provided by [Conda.jl](https://github.com/JuliaPy/Conda.jl).

For `pyimport_conda("scipy.optimize", PKG)`, you should pass the name of the Anaconda package, not the path.   i.e. you should so `pyimport_conda("scipy.optimize", "scipy")`.

Alternatively, if you want Julia to use your other Anaconda installation, you can reconfigure PyCall to do that as [explained in the README](https://github.com/JuliaPy/PyCall.jl#specifying-the-python-version).
