### ISSUE TITLE
Error when using emcee class functions

### ISSUE THREAD

**Issue by nkeito** [JuliaPy/PyCall.jl#449]
I'm trying to use the [MCMC hammer](http://dfm.io/emcee/current/) and I'm repilcating the basic ussage example

`import numpy as np`
`import emcee`

`def lnprob(x, ivar):`
`    return -0.5 * np.sum(ivar * x ** 2)`

`ndim, nwalkers = 10, 100`
`ivar = 1. / np.random.rand(ndim)`
`p0 = [np.random.rand(ndim) for i in range(nwalkers)]`
`sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=[ivar])`
`sampler.run_mcmc(p0, 1000)`

Which in Julia would look like

`using PyCall`
`@pyimport numpy as np`
`@pyimport numpy.random as nr`
`@pyimport emcee`

`function lnprob(x, ivar):`
`    return -0.5 * np.sum(ivar * x ^ 2)`
`end`

`ndim, nwalkers = 10, 100 ;`
`ivar = np.divide(  1. , nr.rand(ndim) );`
`p0 = np.zeros( (nwalkers,ndim) );`

`for i=1:nwalkers`
`	p0[i,:] = nr.rand(ndim)`
`end`
`sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=[ivar])`
`sampler.run_mcmc(p0, 1000)`

But when the last line is excuted, I got the error 
`ERROR: type PyObject has no field run_mcmc`

Actually Julia says that sampler contains a object named o, which has all the standard operations in Julia.

**Comment by stevengj** [comment]
Do `sampler[:run_mcmc](p0, 1000)`.  See the PyCall README.
