### ISSUE TITLE
Inline variable evaluation with py"""..."""

### ISSUE THREAD

**Issue by GearsAD** [JuliaPy/PyCall.jl#451]
Hi,

Given this code:
using PyCall
testString = "A test string"
testInt = 10
py"""
print \"$testString\"
print \"$testInt\"
"""

I'd expect that it would evaluate testString and testInt before passing the string to python, but it doesn't seem to be the case. The output is:
$testString
$testInt

Is that expected behavior, or am I missing something?

Thanks!

**Comment by stevengj** [comment]
`$` is ignored (does not doe interpolation) inside Python string literals and comments, since `"$testString"` is perfectly valid Python code.  If you remove the quotation marks it will do what you expect:
```jl
julia> py"""
       print $testString
       print $testInt
       """
A test string
10
```

**Comment by stevengj** [comment]
To further clarify, in a custom string literal like `py"...."`, Julia itself doesn't do any interpolation at all.  All of the interpolation here is done by the `py_str` macro in PyCall.

The advantage of this is that it allows you to interpolate *values*, not just strings, into Python expressions.  For example, in
```jl
julia> py"$testInt + 3"
13
```
the value of `testInt = 10` is inserted into the Python expression as an integer value, not as a string, so Python can add it to `3` with no problem.

**Comment by GearsAD** [comment]
That's fair - my error was the redundant quotes, I wasn't aware that literals were special cases. 

Thanks for the quick response!
