### ISSUE TITLE
Test Python 3.7.0[a3]? And Julia 0.7/1.0?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPy/PyCall.jl#453]
You can just leave this open if you want to wait for release of Python (and/or Julia). Or if you just can't test alpha.

Are tests needed for Julia 0.7? You could test with most recent 3.6 [and/or 3.7] and oldest supported 3.4.

I said previously you see no reason to NOT test 3.3, but should many combinations with Julia versions be tested?

http://blog.python.org/2017/09/python-337rc1-is-now-available-prior-to.html
"all support for the 3.3 series of releases ends on 2017-09-29"

**Comment by stevengj** [comment]
It is testing with 0.7 (and currently failing, because I haven't updated it for 0.7 yet).
