### ISSUE TITLE
PyObject fails for DiffEqBase.ODESolution object

### ISSUE THREAD

**Issue by zekeriyasari** [JuliaPy/PyCall.jl#460]
I am using [pyjulia](https://github.com/JuliaPy/pyjulia) package to solve  ODE problems in julia  and to get the solution back to python. In the documentation of `pyjulia` its says "PyJulia loads the libjulia library and executes the statements therein. To convert the variables, the PyCall package is used.". The problem with `PyCall` is that it cannot convert the solution object (whose type is `DiffEqBase.ODESolution`) of [DifferentialEquation](https://github.com/JuliaDiffEq/DifferentialEquations.jl)s package into a python object, but it converts the solution object into a python list.  Below is the python script used:
```python
from julia import Julia

jul = Julia()
jul.using("DifferentialEquations")

def f(t, u):
    return -u

u0 = 0.5
tspan = (0., 1.)
prob = jul.ODEProblem(f, u0, tspan)
sol = jul.solve(prob)
print(type(sol))
print(sol)
```
and the output of this script is:
```python
<class 'list'>
[0.5, 0.45240062712255974, 0.35512013172093637, 0.25958279463712797, 0.18393979662768456]
```
However, I tried `PyCall` for a different julia object. For example, the following script:
```julia
using PyCall

struct MyType
    x::Vector
    y::Vector
end

obj = MyType([1., 2.], [3., 4.])
pobj = PyObject(obj)
println(pobj[:x])
```
gives the output:
```julia
[1.0, 2.0]
```
which shows that `PyCall` can actually convert the julia object into a python object. 

So I could not understand what goes wrong when it comes to `DiffEqBase.ODESolution` object. 

Thanks in advance for your interest.

**Comment by stevengj** [comment]
The issue is that `DiffEqBase.ODESolution` is a subtype of `AbstractArray`, so by default it converts to a Python list or array type.

What you apparently want instead is a "wrapped" Julia object.  This is easy to do from Julia by calling `PyCall.pyjlwrap_new(obj)` rather than `PyObject(obj)`.   But I'm not sure if there is any easy way to do this on the pyjulia side; see also #461.

It's not a bug however.  This is the basic problem with automatic conversions between Python and Julia types — sometimes, the conversion picked is not the one you want, and you need a way to specify it manually.

**Comment by stevengj** [comment]
I just added an API to make this easier.  You'll need to check out the latest (master) version of `PyCall` to use it.  Given this, I think you can do something like:

Try
```jl
jul.using("PyCall")
jul.using("DiffEqBase")
solve = jul.pyfunctionret(jul.solve, jul.Any, jul.PyAny)
solve(prob)
```
and get a wrapped ODESolution object back.

**Comment by stevengj** [comment]
(I expect you know this already, but using DifferentialEquations.jl from Python in this way loses almost all of the performance advantages of Julia, because your Python function `f` is in the inner loop.)

**Comment by zekeriyasari** [comment]
I am really grateful for your effort and also the performance tips you gave about specifying the ODE function `f` via a Julia function. But, having checked out master, I tried the new function `pyfunctionret`. Now the new problem is that
```julia
solve = jul.pyfunctionret(jul.solve, jul.Any, jul.PyAny)
```
cannot be executed because python throws the following exception:
```python
Traceback (most recent call last):
  File "/user/zekeriya.sari/Documents/AtomProjects/PyJUlia/python_script.py", line 16, in <module>
    solve = jul.pyfunctionret(jul.solve, jul.Any, jul.PyAny)
AttributeError: 'Julia' object has no attribute 'Any'
``` 
The problem is the same for any other built-in Julia types, as expected. Any suggestions?

**Comment by stevengj** [comment]
See my comment in the other issue you filed.

**Comment by ChrisRackauckas** [comment]
@stevengj I'm trying to follow what the solution was to build a wrapper package. If I am getting this right, I should create a DiffEqPy.jl that reexports most functions but swaps some like `pyfunctionret(sol, argtypes, Any)` so it can return a full object to Python?

**Comment by ChrisRackauckas** [comment]
Nevermind, that worked. Good fix.
