### ISSUE TITLE
Add access to list_running_servers function

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/PyCall.jl#474]
Is there a way to robustly give users access to IPython's `list_running_servers` function?

**Comment by stevengj** [comment]
See [my answer on discourse](https://discourse.julialang.org/t/how-to-get-url-of-current-jupyter-notebook/9851/5?u=stevengj); if this were added anywhere, it would be added in IJulia, not here.

With PyCall, of course, you can `pyimport("IPython")` directly, though it won't give you the running IJulia kernel (which does not use IPython).
