### ISSUE TITLE
Julia 0.7 seemingly infinite series of deprecation warnings

### ISSUE THREAD

**Issue by kafisatz** [JuliaPy/PyCall.jl#478]
I am trying to update some of my code for julia 0.7.

Thus I ran ```include("myPackage.jl")```  which notably is a Module and thus contains no code which is actually run (with the exception of some info commands and the __init()__ function).

This results in the deprecation warnings below which seem to go on for a very long time (I waited at least 3 minutes). My code has `using PyCall`.

Is there any way to get around this?
If I add my Package to the LOAD_PATH variable and the run 'using', I get the same.

I note that I want to check (and improve) the deprecation warnings of my own package.

```
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\v0.7\PyCall\src\pyoperators.jl:53
WARNING: Base.Range is deprecated, use AbstractRange instead.
  likely near C:\Users\bernhard.konig\.julia\v0.7\PyCall\src\pyoperators.jl:53
```

**Comment by mauro3** [comment]
Have you tried running master of PyCall?  There seem to be some 0.7 related commits which happened recently.

**Comment by kafisatz** [comment]
I will try that. I think first starting Julia with --depwarn=no and then 'using' all Packages that I rely on (to precompile), might also be of help here.
Thanks.
