### ISSUE TITLE
When should npyinitialize be called?

### ISSUE THREAD

**Issue by JobJob** [JuliaPy/PyCall.jl#481]
Am I, mr user, supposed to call `npyinitialize()`? I'm guessing not, so this might be a bug.

Seems `asscalar`, and in turn `convert(Int, numpy_array_element::PyObject)`, depends on `npy_number` being initialized
```
using PyCall
@pyimport numpy as np
pyoarr = pycall(np.array, PyObject, 1:3)
el = get(pyoarr, PyObject, 0)

@show pytypeof(el) pytypeof(PyCall.asscalar(el)) PyCall.npy_number
convert(Int, el)
```
outputs
```
pytypeof(el) = PyObject <class 'numpy.int64'>
pytypeof(PyCall.asscalar(el)) = PyObject <class 'numpy.int64'>  (should be int)
PyCall.npy_number = PyObject NULL  (shouldn't be null for asscalar to work)
ERROR: PyError (ccall(@pysym(PyInt_AsSsize_t), Int, (PyPtr,), asscalar(po))) <class 'TypeError'>
TypeError('an integer is required',)
```

**Comment by stevengj** [comment]
No, you are never supposed to call it.  You shouldn't be calling internal functions like `PyCall.asscalar` either.

You can just use 
```jl
julia> pycall(np.asscalar, PyObject, el)
PyObject 1
```
for example.

**Comment by JobJob** [comment]
but is 
```
using PyCall
@pyimport numpy as np
pyoarr = pycall(np.array, PyObject, 1:3)
el = get(pyoarr, PyObject, 0)
convert(Int, el)
```
supposed to work? That calls asscalar, and PyCall.npy_number is PyNULL then

**Comment by stevengj** [comment]
Oh, right, I see the problem.

It actually works fine for me in Python 2.7:
```jl
julia> convert(Int, el)
1
```
but my recollection from 9304bbc5fe6fa00137e1949f104acfc86bedb107 was that the `asscalar` is needed in Python 3.   The current code works if you get numpy arrays via Julia's automatic conversions, but not if you import numpy manually yourself.

**Comment by JobJob** [comment]
Ok cheers, yep I'm on Python 3. Feel free to close this.

**Comment by stevengj** [comment]
No, Python 3 is supported too, so I need to fix this.

**Comment by JobJob** [comment]
Ok, just fyi the actual use case that landed me here was fairly contrived. I was just testing converting an array to a tuple, it wasn't part of any actual work/project.
```
using PyCall
@pyimport numpy as np
arrpytpl = pycall(np.array, Tuple{Vararg{Int}}, 1:10)
```

**Comment by stevengj** [comment]
Should be fixed now.

**Comment by JobJob** [comment]
Thanks for almost fixing this - just tried it and [unsafe_asscalar(o)](https://github.com/JuliaPy/PyCall.jl/commit/96025053355ae47d4b3d2bc430ff924ac39b5113#diff-9bc274dbfe972452e9acafe692c9fd38R28) isn't calling `o.item()`, it's just returning the function `o.item`.

While I'm here, just regarding my PRs - I'm happy enough with them all so you can take another look. I've just rebased them all off master. This issue here is breaking tests locally for them, so we'll need to check again once that's fixed (and I merge/rebase the fix into each of them).

**Comment by stevengj** [comment]
Whoops!  Will make a PR shortly.
