### ISSUE TITLE
Julia in Python

### ISSUE THREAD

**Issue by PeterMortensen93** [JuliaPy/PyCall.jl#488]
I am a totally new to python and Julia, but I need to call julia functions in Python (vOptGeneric, vOptspecific  etc.)
I call Pkg.add("PyCall") in julia prompt and installed julia in python and have run the setup.py.

But when I go into Python (via Spyder) and try to import julia and call j = julia.Julia(), i get following error:
FileNotFoundError: [WinError 2] 

What did I do wrong?

Thank you in advanced.

**Comment by JobJob** [comment]
Hi. I think you're looking for https://github.com/JuliaPy/pyjulia which is the Python package to use to call Julia from Python.

You probably just need to `pip install julia`, but check the installation instructions there. 

If you have any further problems, open an issue at pyjulia. Cheers 🙂
