### ISSUE TITLE
PyJulia

### ISSUE THREAD

**Issue by PeterMortensen93** [JuliaPy/PyCall.jl#491]
I am a totally new to python and Julia, but I need to call julia functions in Python (vOptGeneric, vOptspecific etc.)
I have installed julia in python and have run the setup.py.

But when I go into Python (via Spyder) and try to import julia and call j = julia.Julia(), i get following error:
FileNotFoundError: [WinError 2]

What did I do wrong? 

Thank you in advanced.

**Comment by JobJob** [comment]
Umm... dup of https://github.com/JuliaPy/PyCall.jl/issues/488 ?

This package is primarily for calling python from julia, as I mentioned you should probably open your issue at [pyjulia](https://github.com/JuliaPy/pyjulia/issues) not here, which is PyCall.jl

Anyway I think this is your issue: https://github.com/JuliaPy/pyjulia/issues/114 - you need to add `C:\path\to\julia` to your %PATH% environment variable
