### ISSUE TITLE
OK to remove package condo

### ISSUE THREAD

**Issue by lewisl** [JuliaPy/PyCall.jl#493]
oops... conda autocorrected to condo!

If I remove Conda will PyCall and PyPlot be affected?  My PyCall points to my Python 3.6 installation managed with Homebrew.

The Conda folder is around 800 megabytes and I would like to remove it.  It seems that Conda brings in a huge miniconda or Anaconda footprint.  My Python 3.6 is richly endowed with packages and it is under 600 meg.  These include numpy, matplotlib, and Jupyter (and all its dependencies). I am happily able to use Jupyter with either Python or Julia kernels.

Love having PyCall and PyPlot, which I use as the backend to Plots.jl.  Just don't need 3 Pythons on my system if possible.

Thanks.

**Comment by stevengj** [comment]
The Conda.jl package itself is tiny — it only installs miniconda if you actually use it.  However, if you used it at one point and then switched to a different Python, miniconda doesn't get removed.

If you are using PyCall and Jupyter with your Homebrew Python, then you don't need the miniconda installation.  You can delete it with
```jl
rm(Pkg.dir("Conda", "deps", "usr"), recursive=true)
```
(It will not be reinstalled unless a package actually uses it.)

You can't delete the Conda.jl package itself, but it is tiny if there is no miniconda install.
