### ISSUE TITLE
Error in using basemap from Python in Julia

### ISSUE THREAD

**Issue by GauravDoshi9** [JuliaPy/PyCall.jl#494]
I am trying to draw a map using Python's basemap in Julia following [this](https://gist.github.com/jpwspicer/bd738886467c56c5d029).

I have succeeded in installing Basemap, and create the basemap object using: 
using PyPlot, PyCall
@pyimport mpl_toolkits.basemap as basemap
map = basemap.Basemap(projection="ortho", lat_0=45, lon_0=-100, resolution="l")
```
PyObject <mpl_toolkits.basemap.Basemap object at 0x13e986490>
```
However, when I try to add coastlines and boundaries, I get the following error:
```
# Draw coastlines, country boundaries, fill continents.
map[:drawcoastlines](linewidth=0.25)
map[:drawcountries](linewidth=0.25)
map[:fillcontinents](color="coral",lake_color="aqua")

PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, kw)) <type 'exceptions.AttributeError'>
AttributeError("'AxesSubplot' object has no attribute 'get_axis_bgcolor'",)
  File "/Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 1861, in drawcoastlines
    self.set_axes_limits(ax=ax)
  File "/Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 3180, in set_axes_limits
    limb2 = self.drawmapboundary(linewidth=0)
  File "/Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 1623, in drawmapboundary
    fill_color = ax.get_axis_bgcolor()
```
Does anybody know what's messing up here? My guess is there is something wrong with `[:drawcoastlines]`, `[:drawcountries]`, and `[:fillcontinents]` but I'm not sure how to correct it?

**Comment by stevengj** [comment]
Looks like matplotlib/basemap#394

**Comment by GauravDoshi9** [comment]
I'm sorry, but can you tell me how to use `conda-forge` as a binary provider (like we can do with `conda`) to use the `basemap` package in `Julia`? I tried searching for it, but can't find anything.

**Comment by stevengj** [comment]
```
using Conda
Conda.add_channel("conda-forge")
Conda.add("basemap")
```
