### ISSUE TITLE
PyCall deadlock?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#498]
In diffeqpy, we encountered the problem that loading a Julia module with PyCall randomly deadlocks https://github.com/JuliaDiffEq/diffeqpy/issues/20  The reason why I think it's PyCall related is that it consistently appears in the traceback when it hangs (see below).

I have no idea when the stall occur. The only when I reproduce it is to repeatedly run `julia -e 'using DiffEqPy'`.

Note that [DiffEqPy.jl](https://github.com/JuliaDiffEq/DiffEqPy.jl/blob/master/src/DiffEqPy.jl) at the moment is very simple and not doing very much:

```julia
module DiffEqPy

using Reexport
@reexport using DifferentialEquations
using PyCall
pysolve = PyCall.pyfunctionret(solve,Any,PyCall.PyAny)

export pysolve

@pyimport inspect
function DiffEqBase.numargs(f::PyCall.PyObject)
    haskey(f,:py_func) ? _f = f[:py_func] : _f = f
    if PyCall.pyversion < v"3.0.0"
        return length(first(inspect.getargspec(_f)))
    else
        return length(first(inspect.getfullargspec(_f)))
    end
end

end # module
```

How should I debug it?

cc: @ChrisRackauckas

### Some random things I've tried:

When it occurs, `sudo strace -p <pid>` shows something like

    futex(0x7f507c45caa0, FUTEX_WAIT_PRIVATE, 2, NULL

though I'm not sure if it helps.  If I run

```sh
while julia -e 'using DiffEqPy'
do
:
done |& tee out.log
```

wait until it stalls, then SIGTERM it, I can get a long traceback in out.log.  It starts with:

```
signal (15): Terminated
while loading /home/takafumi/.julia/v0.6/DiffEqPy/src/DiffEqPy.jl, in expression starting on line 497
unknown function (ip: 0x7f190b0fcfd8)
__libc_malloc at /usr/lib/libc.so.6 (unknown line)
save_env at /buildworker/worker/package_linux64/build/src/subtype.c:142
intersect_unionall at /buildworker/worker/package_linux64/build/src/subtype.c:1557
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:1954
intersect_unionall_ at /buildworker/worker/package_linux64/build/src/subtype.c:1513 [inlined]
intersect_unionall at /buildworker/worker/package_linux64/build/src/subtype.c:1558
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:1954
intersect_all at /buildworker/worker/package_linux64/build/src/subtype.c:2040
jl_type_intersection_env_s at /buildworker/worker/package_linux64/build/src/subtype.c:2147
jl_typemap_assoc_by_type_ at /buildworker/worker/package_linux64/build/src/typemap.c:600
jl_typemap_assoc_by_type at /buildworker/worker/package_linux64/build/src/typemap.c:745
jl_mt_assoc_by_type at /buildworker/worker/package_linux64/build/src/gf.c:1038
jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:1894 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1923
next at /home/takafumi/.julia/v0.6/PyCall/src/conversions.jl:533
copy at ./associative.jl:114
unknown function (ip: 0x7f18f33a0152)
```

I'm using:

```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

with PyCall.jl master.

**Comment by stevengj** [comment]
True, but in general I would recommend against `@pyimport` anyway.  It is slow because it tries to import *every* symbol in the library and convert it to a Julia object, and it can also be problematic if there is something weird in the module that somehow triggers a PyCall problem or bug upon conversion, e.g. a lazy container that pretends to be an array but has `typemax(UInt32)`  length.

`@pyimport inspect` works fine on my machine with Python 2.7, but maybe it causes a problem with a newer Python version.

**Comment by stevengj** [comment]
Your `module DiffEqPy` example works fine for me (Mac with Python 2.7)

**Comment by ChrisRackauckas** [comment]
It works for me too, most of the time. Every once in awhile it stalls though. That's what @tkf is pointing out: to hit the bug you need to repeat `using DiffEqPy` a bunch, or from Python if you run:

```py
import diffeqpy
de = diffeqpy.setup()
```

it can stall, while

```py
import julia
julia.Julia()
import diffeqpy
de = diffeqpy.setup()
```

it has a higher success rate. So there's something going on... I'll get rid of the `@pyimport` and see if that works.

**Comment by tkf** [comment]
@stevengj Thanks. It explains why the stall happens when iterating over a dict.

**Comment by tkf** [comment]
Indeed, removing `@pyimport inspect` https://github.com/JuliaDiffEq/DiffEqPy.jl/commit/050a088bb2a69355800503b717c8945c24d05089 seems to fixed the problem.  I can now run `julia -e 'using DiffEqPy'` more than 10 times in a row without the deadlock.

Thanks for the help!
