### ISSUE TITLE
Conversion of symbolic variable

### ISSUE THREAD

**Issue by moesphere** [JuliaPy/PyCall.jl#510]
Running the following code raises an error with Python 3, but not with Python 2 (in my case).

```julia
using PyCall, SymPy
convert(Int64, PyObject(Sym(1)))
```

The error message is
```julia
ERROR: PyError (PyLong_AsSsize_t) None
```

Any ideas?

**Comment by stevengj** [comment]
This is similar to #481 — the Python 3 integer conversion function is apparently more picky about something being an integer type.

**Comment by stevengj** [comment]
Hmm, `Sym(1).x["__int__"]` exists, so `int()` works in Python.   I need a C API function that uses `__int__()` if necessary...

**Comment by moesphere** [comment]
I am not an expert in Python and I do not know if that helps. Anyways, according to the python documentation,
in Python 3 all integers are implemented as “long” integer objects of arbitrary size, see https://docs.python.org/3.5/c-api/long.html.
The convert function in PyCall calls PyInt_AsSsize_t(). I can find this function in the Python 2 docs but not in the Python 3 docs. The Python 3 pendant seems to be PyLong_AsSsize_t().

**Comment by stevengj** [comment]
Hmm, seems like I should be calling `PyLong_AsLongLong` rather than `PyLong_AsSsize_t`.

**Comment by moesphere** [comment]
That works. I replaced `PyLong_AsSsize_t` with `PyLong_AsLongLong` in the `startup.jl` file.

**Comment by stevengj** [comment]
> I replaced PyLong_AsSsize_t with PyLong_AsLongLong in the startup.jl file

That only works on 64-bit machines; on 32-bit machines, the return types are different.

PR #511 should be a proper fix.

**Comment by moesphere** [comment]
Great, thanks!
