### ISSUE TITLE
Cannot use `@pydef` for classes with static attributes

### ISSUE THREAD

**Issue by galenlynch** [JuliaPy/PyCall.jl#513]
It seems that `@pydef` does not work for classes with static attributes:

```julia
julia> @pydef mutable struct Foo
           class_attr = 1
           function __init__(self)
               println(self[:class_attr])
           end
       end

ERROR: AssertionError: Not a function definition: class_attr = 1
```

**Comment by AlphaFase** [comment]
emmmmm,   Pydef is the def in Python.

eg:
```
def xx:
   pass
```

**Comment by galenlynch** [comment]
This portion of the documentation says you can define python classes using `@pydef`: [see here](https://github.com/JuliaPy/PyCall.jl#defining-python-classes)

However, you cannot use [class variables](https://docs.python.org/2/tutorial/classes.html#class-and-instance-variables) in the class definition using the syntax above. Looking at the implementation of `@pydef` makes me think that class variables are not supported, and it is not merely a matter of using the right syntax.

**Comment by galenlynch** [comment]
It seems like it would be simple to extend [def_py_class](https://github.com/JuliaPy/PyCall.jl/blob/28f75b023cba73348ee2d151ea786a7bb9697178/src/pyclass.jl#L25) to include type variables, which can be created with the python built-in [type](https://docs.python.org/3/library/functions.html#type). Then it would be a matter of changing the `@pydef` and `@pydef_object` macros to support some syntax for creating class variables, perhaps something like:

```julia
@pydef mutable struct Counter
    num_obj = 0 # class variable
    function __init__(self)
        Counter[:num_obj] += 1
    end
end
```

As a work-around, I believe you should be able to add class variables to existing types using the python built-in [setattr](https://docs.python.org/3/library/functions.html#setattr).
