### ISSUE TITLE
linspace is not defined

### ISSUE THREAD

**Issue by jimibengbeng** [JuliaPy/PyCall.jl#518]
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));

ERROR: UndefVarError: linspace not defined

**Comment by ivarne** [comment]
See https://docs.julialang.org/en/v0.7.0/NEWS/#Deprecated-or-removed-1

It hase been removed in 1.0 and you should use ``range(0, stop=2pi, length=1000)``

**Comment by jimibengbeng** [comment]
thanks！

**Comment by stevengj** [comment]
Documentation fixed in #522
