### ISSUE TITLE
Build failure for python3 on 1.0

### ISSUE THREAD

**Issue by mortenpi** [JuliaPy/PyCall.jl#523]
Running into the following build error on Julia 1.0 on Ubuntu 18.04, with PyCall v1.17.1 and master when `PYTHON=python3`:

```
pkg> build PyCall
  Building Conda ─→ `~/.julia/packages/Conda/m7vem/deps/build.log`
  Building PyCall → `~/.julia/packages/PyCall/DkwHa/deps/build.log`
┌ Error: Error building `PyCall`:
│ ERROR: LoadError: Couldn't find libpython; check your PYTHON environment variable.
│ 
│ The python executable we tried was python3 (= version 3.6);
│ the library names we tried were ["libpython3.6m.so", "libpython3.6m", "libpython3.6", "libpython"]
│ and the library paths we tried were AbstractString["/usr/lib", "/usr/lib", "/usr", "/usr/lib"]
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] find_libpython(::String) at /home/mortenpi/.julia/packages/PyCall/DkwHa/deps/build.jl:129
...
│ in expression starting at /home/mortenpi/.julia/packages/PyCall/DkwHa/deps/build.jl:170
```

Now, the interesting thing is that `PYTHON=python` builds just fine, and both build just fine on Julia 0.7. Not sure why it can figure out Python 2, but not Python 3. They are both installed via apt and the `.so` files live in the same directory:

```
$ ls /usr/lib/x86_64-linux-gnu/libpython*
/usr/lib/x86_64-linux-gnu/libpython2.7.a
/usr/lib/x86_64-linux-gnu/libpython2.7.so
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
/usr/lib/x86_64-linux-gnu/libpython3.6m.a
/usr/lib/x86_64-linux-gnu/libpython3.6m.so
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
```

```
$ python --version
Python 2.7.15rc1
$ python3 --version
Python 3.6.5
```

**Comment by stevengj** [comment]
Can you try the latest (git master) version?  (`dev PyCall` at the pkg prompt) … PyCall wasn't compatible with 1.0 until tonight (#522).

**Comment by mortenpi** [comment]
Tried with dcfe585248e1278e0a099726f7c0f52ffe122d3c checked out, but the issue is still there.

**Comment by stevengj** [comment]
It seems to be not looking in the right library path.    It tries to look in the path Python tells it, via `distutils.sysconfig.get_config_var('LIBDIR')` and `distutils.sysconfig.get_config_var('LDFLAGS')`,, but apparently Python's LIBDIR is not correct on your machine.

**Comment by stevengj** [comment]
Maybe I should just use `ldd` on Linux.

**Comment by stevengj** [comment]
Hmm, but that doesn't explain why it would work on 0.7.

**Comment by stevengj** [comment]
Can you try with `ENV["PYCALL_DEBUG_BUILD"]="yes"`?

**Comment by mortenpi** [comment]
Here's the output: https://gist.github.com/mortenpi/3308b9b90899f02636339890c9ae6dd6

**Comment by mortenpi** [comment]
Also, in case this is useful:

```
$ python -c'import distutils.sysconfig; print distutils.sysconfig.get_config_var("LIBDIR")'
/usr/lib
$ python3 -c'import distutils.sysconfig; print(distutils.sysconfig.get_config_var("LIBDIR"))'
/usr/lib
```

There are no Python shared libraries directly under `/usr/lib`, and instead they live under `/usr/lib/x86_64-linux-gnu/` for both Python 2 and 3. So it looks like there is no difference between 2 and 3, but `ENV["PYTHON"]="python"` builds without problems somehow.

**Comment by mortenpi** [comment]
Oh, I think this is the problem (from the Gist):

```
dlopen(libpython3.6m) ==> ErrorException("could not load library \"libpython3.6m\"\n/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libpython3.6m.so)")
```

And the reason it is searching for the `libc` in the `/snap` directory is because I am installing Julia as a snap package on my system. And the `libc.so.6` are different between `/lib` and `/snap/core/current/lib`:

```
md5sum:
5d8e5f37ada3fc853363a4f3f631a41a  /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
50390b2ae8aaa73c47745040f54e602f  /lib/x86_64-linux-gnu/libc.so.6
```

When I run Julia from an extracted tarball then everything is fine. So this has to do with how the system and Snappy libraries interact and is specific to my setup. I need to figure out if there's anything that can be done to make this work as expected.

For now though, I don't think there's anything actionable here in PyCall for this, so I'll close the issue. Thanks for helping with the debug!
