### ISSUE TITLE
Support run-time interpreter configuration?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#528]
(I'm asking this before seriously reading PyCall.jl since @stevengj or someone else may/can answer it with a simple No. :grin:)

Using PyJulia with Julia 1.0 is now very hard especially in Conda and Ubuntu https://github.com/JuliaPy/pyjulia/issues/185.  PyJulia needs the "hack" using `Base.DEPOT_PATH` https://github.com/JuliaPy/pyjulia/issues/173 or waits for `julia` core support https://github.com/JuliaLang/julia/issues/28518.

*If* PyCall.jl can support run-time configuration of Python interpreter, it will be much easier since PyJulia can just reuse the same precompilation cache.  If it is possible, it is much more appealing to me than implementing a bulky `Base.DEPOT_PATH` hack which would be obsolete once `julia` core provides more straightforward support.

In PyCall.jl, I see there are many `const` and `macro` that depends on the Python interpreter.  But is run-time simple `if` branch *that* costly compared to Python interpreter?  Also isn't it possible to embed (a reference to) such information in (say) `PyObject` so that no branching would happen after initialization?

Or are there other reasons than rum-time speed?  Reducing JIT time or something?  (Just guessing from #167)  Would parametrizing types with Python major version and `precompile`ing for both versions solve it?  (Or simply drop Python 2 support?)

**Comment by mprogram** [comment]
I cast my vote on dropping Python 2 support in favor of PyCall.jl ability to work with Python 3's lack of `libpython3` in its `ldd` output 😁

**Comment by stevengj** [comment]
The main reason I switched to build-time configuration of libpython was to reduce load time.  I used to identify `libpython` at runtime, and it was way slower to do `using PyCall`.

**Comment by stevengj** [comment]
It seems like it would be better to just set up a separate depot or similar for pyjulia.

**Comment by tkf** [comment]
Yeah, I think you are right. My suggestions would be solved by `julia` core in a much more general way if it implements package options. Implementing it manually in PyCall.jl seems to be too much work for a premature optimization.
