### ISSUE TITLE
Can you add some macro like @rget and @rput in RCall.jl

### ISSUE THREAD

**Issue by 229668880** [JuliaPy/PyCall.jl#539]
Hi, there are two convenient macro in RCall.jl, @rget and @rput, by which we can transfer variables between Julia and R without worrying about how to build a new variable in R and then copy data in Julia to it.

Could you add something like them in PyCall.jl? I tried to do it, but failed, because it hard to build a new variable in Python with py"...". 

py"""...""" could do it, but I have to use it in multiple lines like this:
py"""
 codes
"""
For example, there is a variable a=1233456 in Julia, then use "@pyput a" to automatically create a variable named "a" in Python and initialize it with 12345. How to realize this macro? 

Thanks

**Comment by tkf** [comment]
After #517 (cc @crstnbr), I guess you can just do:

```julia
main = pyimport("__main__")
main.a = 12345
```

**Comment by stevengj** [comment]
@tkf is right, and you can currently do `main[:a] = a`.  You also can also do
```jl
julia> py"""
       a = $a
       """
```

I don't see a need for a more specialized syntax here, as creating global variables in Python, outside of `py""" ... """` blocks, is not commonly needed to call Python code.
