### ISSUE TITLE
@pyimport on julia 1.0: ERROR: syntax: unsupported `const` declaration on local variable 

### ISSUE THREAD

**Issue by jbrea** [JuliaPy/PyCall.jl#541]
On julia 1.0, with PyCall#master I get
```julia
julia> using PyCall

julia> try
           @pyimport pip
       catch
           println("failed")
       end
ERROR: syntax: unsupported `const` declaration on local variable around /home/j/.julia/packages/PyCall/lhrke/src/PyCall.jl:526

julia> @pyimport pip

julia> 
```

**Comment by stevengj** [comment]
Put a `global pip` statement in the `try` block.    See also JuliaLang/julia#28789

`@pyimport` is going away in the near future anyway — see also #517.    You will just do `pip = pyimport("pip")`, and the scoping will be explicit.
