### ISSUE TITLE
Memory leak with different libraries (numpy, pyTorch, OpenAI Gym)

### ISSUE THREAD

**Issue by Paethon** [JuliaPy/PyCall.jl#542]
I am currently working with OpenAI Gym using PyCall and the following code (randomly plays games of Atari 2600 Pong) uses up memory it never frees (on the order of 100MiB a second).

```julia
using PyCall

@pyimport gym
env = gym.make("Pong-v0")
env[:reset]()

for i in 1:100000
    obs, reward, done, info = env[:step](rand([3,4]))
    env[:render]()
    done && env[:reset]()
end

env[:close]()
```
To try you should `pip install gym[all]`

The same example in Python does not have this problem. Any idea how to fix this? Or how do I find out what exactly is happening here?

This seems to occur with other libraries (numpy, PyTorch) as well. See later comments on this issue.

**Comment by Paethon** [comment]
Thank's for the starting point. I will have a look and report back.

**Comment by boathit** [comment]
I could also provide a minimal code for the test
```julia
using PyCall
@pyimport torch

for i = 1:10_000
    X = torch.rand(500, 500)
    i % 1000 == 0 && (println("i: $i"); sleep(2))
end
```
It seems the memory held by `X` will never be released.

Any chance to fix this?

**Comment by Paethon** [comment]
Thank you! #558 has fixed the issue for me!

**Comment by JobJob** [comment]
Aside: @Paethon you might be interested in [OpenAIGym.jl](https://github.com/JuliaML/OpenAIGym.jl) and [this PR](https://github.com/JuliaML/OpenAIGym.jl/pull/13) if you want performant access to the Gym from Julia.

**Comment by Paethon** [comment]
@JobJob Thanks, will have a look!
