### ISSUE TITLE
segmentation fault when using opencv after Julia0.7

### ISSUE THREAD

**Issue by longqian95** [JuliaPy/PyCall.jl#545]
In "T.jl" file:
```
module T
using PyCall
@pyimport cv2
t()=cv2.__version__
end
```
Add the location to LOAD_PATH (or make a package), and run `using T; T.t()` in Julia0.7/1.0/master. It will show "incremental compilation may be broken for this module" and "segmentation fault".

There is no problem in Julia0.6.

If just paste the code into REPL and run `T.t()`, then there is no problem for any Julia version.

`Pkg.installed()["PyCall"]`: v1.18.4
`PyCall.pyversion`: v2.7.15
`cv2.__version__`: 2.4.13.5

**Comment by stevengj** [comment]
Don't use `@pyimport` in modules, because it is not precompile safe.  The right way to do it is explained in the README.

The difference in 0.7/1.0 is that precompiling is now the default, hence the error.
