### ISSUE TITLE
Fails to precompile on macOS X 10.13.6 and Julia v1.0

### ISSUE THREAD

**Issue by JBlaschke** [JuliaPy/PyCall.jl#547]
When I try to import `PyCall` I get the following error:

```julia
julia> import PyCall
[ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
ERROR: LoadError: LoadError: could not load library "/Users/johannesblaschke/.julia/packages/Conda/m7vem/deps/usr/lib/libpython3.6m"
dlopen(/Users/johannesblaschke/.julia/packages/Conda/m7vem/deps/usr/lib/libpython3.6m.dylib, 9): image not found
```

I looked for `.julia/packages/Conda/m7vem/deps/usr/lib/libpython3.6m.dylib` and could only find `libpython3.7m.dylib`. Maybe update the package?

**Comment by tkf** [comment]
I'd try re-building PyCall first by `]build PyCall` (or `Pkg.build("PyCall")`).

**Comment by JBlaschke** [comment]
Cool! It works now. Thanks for the info. I was running into this problem when importing PyPlot.jl
