### ISSUE TITLE
On anaconda_conda

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#560]
I propose to stop unconditionally installing conda packages in `pyimport_conda` when Conda.jl is not used:

https://github.com/JuliaPy/PyCall.jl/blob/49029e0347a550ca15df06558fe5aad9ca80479a/src/PyCall.jl#L657-L663

If a user explicitly sets `$PYTHON` then it means s/he do not want auto-magical handling of Python packages by Conda.jl.  Installing package automatically at runtime is not what programmers would expect, I hope (unless, say, there is some integrity check like GPG verification).  I can think of several options to fix it:

1. Let `CONDA_JL_HOME` handle this case and remove this `if !isempty(aconda)` branch.
2. Print an error message with instruction to install appropriate packages.
3. If `isinteractive()` then prompt user before executing `conda install`.

If you are going to take an option like 3, I think there is one more thing to be fixed:

https://github.com/JuliaPy/PyCall.jl/blob/49029e0347a550ca15df06558fe5aad9ca80479a/src/PyCall.jl#L662-L663

I don't think any package should modify user's configuration silently.  Why not use `conda install --channel $channel ...` like this?:

```julia
options = ``
if isempty(channel)
    options = `--channel $channel`
end
run(`$aconda install -y $options $condapkg`)
```

**Comment by stevengj** [comment]
I'm okay with removing the `if !isempty(aconda)` branch and just replacing it with an exception that suggests what `conda` command to run.
