### ISSUE TITLE
Reference to `PyPlot.Figure` is still stolen

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#567]
The same bug I reported in #551 still happens with `PyPlot.Figure` (and probably with `SymPy.jl`, `Pandas.jl`, etc.):

```julia
julia> using PyCall, PyPlot

julia> fig = gcf()
Figure(PyObject <Figure size 666x1002 with 1 Axes>)

julia> py"""
       ns = {}
       def set(name):
           ns[name] = $include_string($Main, name)
       """

julia> py"set"("fig")

julia> fig
Figure(PyObject NULL)
```

The fix to #551 in #553 was

https://github.com/JuliaPy/PyCall.jl/blob/0f685cf02b6214ffc40b0aba7ab657749d587f5a/src/PyCall.jl#L143-L144

but `PyPlot` "smuggles" the refcount to Python via `pyreturn(x::Any)` path since [`PyObject(f::Figure)` just unwraps the internal `PyObject`](https://github.com/JuliaPy/PyPlot.jl/blob/daadae458ecb696e29c45636d91a9e7b7eddc246/src/PyPlot.jl#L56):

```julia
PyObject(f::Figure) = f.o
```

I wonder what's the best approach.  It would be bad if all `JuliaPy/*.jl` packages have to care about refcounts...  Maybe define an `AbstractPyObject` type and let people define "wrappers" by inheriting from it?

```julia
# --- PyCall.jl
abstract type AbstractPyObject end
pyreturn(x::AbstractPyObject) = pyincref_(PyObject(x))

# --- PyPlot.jl
mutable struct Figure <: AbstractPyObject
    o::PyObject
end
PyObject(f::Figure) = f.o
```

It still feels a bit dangerous that `PyObject` may create a new reference or returning existing one.  Maybe add an interface method (say) `pyunwrap` to be overloaded for `AbstractPyObject` subtypes which mixes-in a safer `PyObject` constructor?

```julia
# --- PyCall.jl
function pyunwrap end
abstract type AbstractPyObject end

PyObject(x::AbstractPyObject) = pyincref(pyunwrap(x).o)

pyreturn(x::AbstractPyObject) = pyincref_(pyunwrap(x))

# --- PyPlot.jl
mutable struct Figure <: AbstractPyObject
    o::PyObject
end
pyunwrap(f::Figure) = f.o  # define pyunwrap instead of PyObject
```

This sounds right since `invoke(pyreturn, Tuple{Any}, f)` where `f::Figure` still works (I think).

**Comment by tkf** [comment]
I just realized that inheritance approach is bad when it's natural for the Python wrapper to inherit some other abstract type such as in `PyDict`:

https://github.com/JuliaPy/PyCall.jl/blob/28f75b023cba73348ee2d151ea786a7bb9697178/src/conversions.jl#L435-L436

So I guess we need to use traits like `IsPyObject(::Type{Figure}) = Val{true}()`?

Defining all the interfaces by hand at this point is cumbersome so it'd be nice to provide a macro like this:

```julia
@pywrapper mutable struct CustomWrapper
    extra_field
    ...
end
```

which is lowered into

```julia
mutable struct CustomWrapper
    o::PyObject
    extra_field
    ...
end
pyunwrap(x::CustomWrapper) = x.o
IsPyObject(::Type{<:CustomWrapper}) = Val{true}()
```

**Comment by stevengj** [comment]
Yeah, it seems like we need an IsPyObject trait of some kind.

**Comment by stevengj** [comment]
The simplest safe thing we could do would be to change the definition to
```jl
pyreturn(x) = PyPtr(pyincref(PyObject(x)))
```
That is, always increment the reference count rather than calling `pystealref!`.   This may cause `PyObject(x)` to live a bit longer (since it won't be deallocated until Julia GC runs *and* the Python caller decrefs it), but I guess that's not a big deal?

**Comment by tkf** [comment]
It seem to be a very good idea to me as it does not require complicated trait system while handling both wrapped and converted case (but, to be honest, I think I lost the level of confidence on the detail of refcount).  Anyway, #631 seem to pass the CI test (except for some external failures).  I just checked locally that my example above also works with #631.  So I think it's good to go.
