### ISSUE TITLE
The mechanism behind data transfer from julia to python

### ISSUE THREAD

**Issue by 229668880** [JuliaPy/PyCall.jl#582]
Create an Array in Julia, then call it within py"""  $x “”“. I am wondering about the mechanism behind it.
Is it transfer data by value or by address?

Suppose there is a very big Array in Julia. Does PyCall copy the data in Array to Python? or just a ref?

**Comment by tkf** [comment]
It's written in README:

> Assuming you have NumPy installed (true by default if you use Conda), then a Julia a::Array of NumPy-compatible elements is converted by PyObject(a) into a NumPy wrapper for the same data, i.e. without copying the data. Julia arrays are stored in column-major order, and since NumPy supports column-major arrays this is not a problem.

--- https://github.com/JuliaPy/PyCall.jl#from-julia-to-python

The values are appropriately converted or wrapped in various contexts:

```julia
# Setting to a Python object:
pyimport("__main__")[:x] = [1, 2, 3]
@assert py"x" == [1, 2, 3]

# Calling a Python function:
py"""
def add_one_inplace(xs):
    xs += 1
"""
xs = [1, 2, 3]
py"add_one_inplace"(xs)
@assert xs == [2, 3, 4]
```

If you want to learn the magic behind `py` macro, run `@macroexpand py"$x"`.
