### ISSUE TITLE
Relase v1.18.5?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#586]
@andreasnoack said it has been causing the trouble in CIBot  https://github.com/JuliaPy/PyCall.jl/issues/565#issuecomment-426400356

@stevengj What do you think? There has been just bugfixes so I think it's just a simple patch number bump.

**Comment by stevengj** [comment]
tagged

**Comment by tkf** [comment]
...and now it's merged! Thanks a lot!
