### ISSUE TITLE
Access user-defined disctionary?

### ISSUE THREAD

**Issue by Moelf** [JuliaPy/PyCall.jl#587]
I'm trying to access elements defined by [uproot](https://github.com/scikit-hep/uproot)
```Python
import uproot
zmumu = uproot.open("Zmumu.root")["events"]
```

In julia, this won't work:
```Julia
using PyCall
@pyimport uproot
zmumu = uproot.open("Zmumu.root")
#PyObject <ROOTDirectory b'Zmumu.root' at 0x7fcd6c4ac518>

uproot.open("Zmumu.root")["events"]
#ERROR: KeyError: key "events" not found
```

**Comment by tkf** [comment]
I'm not sure if there is a direct interface to do it.  If you are lucky,

```julia
PyDict(uproot.open("Zmumu.root"))["events"]
```

may work. Otherwise:

```julia
getitem = pyimport("operator")[:getitem]
getitem(uproot.open("Zmumu.root"), "events")
```

You can also do `setitem = pyimport("operator")[:setitem]`

**Comment by Moelf** [comment]
In the python version, the `zmumu = uproot.open("Zmumu.root")["events"]` is actually another object, it has a function, for example, called `show()`, in julia it seems that the object got converted to array.

**Comment by tkf** [comment]
You can use `pycall` to bypass PyCall's automatic-conversion:

```julia
pycall(getitem, PyObject, uproot.open("Zmumu.root"), "events")
@pycall getitem(uproot.open("Zmumu.root"), "events")::PyObject  # equivalent
```

**Comment by stevengj** [comment]
The currently documented way is to do `get(uproot.open("Zmumu.root"), PyObject, "events")`
