### ISSUE TITLE
LoadError: Couldn't find libpython

### ISSUE THREAD

**Issue by MMalakhov** [JuliaPy/PyCall.jl#588]
I can't build PyCall on linux mint 18.3

> 
> julia> Pkg.build("PyCall")
>   Building Conda ─→ `~/.julia/packages/Conda/hsaaN/deps/build.log`
>   Building PyCall → `~/.julia/packages/PyCall/rUul9/deps/build.log`
> ┌ Error: Error building `PyCall`: 
> │ ERROR: LoadError: Couldn't find libpython; check your PYTHON environment variable.
> │ 
> │ The python executable we tried was python3 (= version 3.5);
> │ the library names we tried were ["libpython3.5m.so", "libpython3.5m", "libpython3.5", "libpython"]
> │ and the library paths we tried were AbstractString["/usr/lib", "/usr/lib", "/usr", "/usr/lib"]
> │ Stacktrace:
> │  [1] error(::String) at ./error.jl:33
> │  [2] find_libpython(::String) at /home/mikhail/.julia/packages/PyCall/rUul9/deps/build.jl:129
> │  [3] top-level scope at logging.jl:313
> │  [4] top-level scope at /home/mikhail/.julia/packages/PyCall/rUul9/deps/build.jl:196
> │  [5] include at ./boot.jl:317 [inlined]
> │  [6] include_relative(::Module, ::String) at ./loading.jl:1041
> │  [7] include(::Module, ::String) at ./sysimg.jl:29
> │  [8] include(::String) at ./client.jl:388
> │  [9] top-level scope at none:0
> │ in expression starting at /home/mikhail/.julia/packages/PyCall/rUul9/deps/build.jl:170
> └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
> 

I have python3.5 at /usr/local/lib

And yes, I saw https://github.com/JuliaPy/PyCall.jl/issues/565 and https://github.com/JuliaPy/PyCall.jl/pull/556
They write that solved issue. But I don't understand what to do, I'm not such cool programmer as you.

PS
I installed everything without problems in May, what happened?

**Comment by tkf** [comment]
The fix is not released yet. See #586

If you can't wait the release, you can use `]add PyCall#master` (see `]?add` for what it means).

**Comment by tkf** [comment]
Should be fixed now #586.
