### ISSUE TITLE
Iterate `PyObject` without conversion

### ISSUE THREAD

**Issue by jw3126** [JuliaPy/PyCall.jl#593]
I am in a situation, where I want to iterate over a `PyObject`, without converting the items into julia objects.
My quick and dirty solution was to copy the `iterate` code and remove the conversion here:
https://github.com/JuliaPy/PyCall.jl/blob/ae9bbba3c54958d6762f90782c5630daa6386c54/src/pyiterator.jl#L37

Is there a better way? Would you like a PR that adds a lower level function without conversion (say pyiterate) and makes `iterate` a stub that just adds convert on top of this function?

**Comment by tkf** [comment]
a dup of #153
see also #507

**Comment by tkf** [comment]
closed by #594 (thanks!)
