### ISSUE TITLE
set ENV["PYTHON"] doesn't work

### ISSUE THREAD

**Issue by daxinnan** [JuliaPy/PyCall.jl#598]
My versioninfo is 
`versioninfo()`
`Julia Version 1.0.1`
`Commit 0d713926f8* (2018-09-29 19:05 UTC)`
`Platform Info:`
`OS: Linux (x86_64-redhat-linux)`
`CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz`
`WORD_SIZE: 64`
`LIBM: libopenlibm`
`LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)`
I have installed Anaconda, and run `conda install tensorflow`, then I set `ENV["PYTHON"]="/my/path/anaconda3/bin/python"`, and I run `build TensorFlow`,and trouble comes

> julia> Pkg.build("TensorFlow")
  Building Arpack ──────────→ `~/.julia/packages/Arpack/UiiMc/deps/build.log`
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/sXbz6/deps/build.log`
  Building Rmath ───────────→ `~/.julia/packages/Rmath/Py9gH/deps/build.log`
  Building Conda ───────────→ `~/.julia/packages/Conda/uQitS/deps/build.log`
  Building MbedTLS ─────────→ `~/.julia/packages/MbedTLS/mkHpa/deps/build.log`
  Building PyCall ──────────→ `~/.julia/packages/PyCall/0jMpb/deps/build.log`
  Building CodecZlib ───────→ `~/.julia/packages/CodecZlib/wwgbh/deps/build.log`
  Building TensorFlow ──────→ `~/.julia/packages/TensorFlow/A6TdG/deps/build.log`
┌ Error: Error building `TensorFlow`:
│ [ Info: Building TensorFlow.jl for CPU use only. To enable the GPU, set the TF_USE_GPU environment variable to 1 and rebuild TensorFlow.jl
│ ERROR: LoadError: Python TensorFlow not installed
│ Please either:
│  - Rebuild PyCall to use Conda, by running in the julia REPL:
│     - `ENV["PYTHON"]=""; Pkg.build("PyCall"); Pkg.build("TensorFlow")`
│  - Or install the python binding yourself, eg by running pip
│     - `pip install tensorflow`
│     - then rebuilding TensorFlow.jl via `Pkg.build("TensorFlow")` in the julia REPL
│     - make sure you run the right pip, for the instance of python that PyCall is looking at.
│
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /blabla/.julia/packages/TensorFlow/A6TdG/deps/build.jl:48
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1041
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at /blabla/.julia/packages/TensorFlow/A6TdG/deps/build.jl:39
└ @ Pkg.Operations /xxxx/download/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
Can't I use system anaconda?

**Comment by daxinnan** [comment]
I know that if I run `ENV["PYTHON"]=""; Pkg.build("PyCall");`, it will download a miniconda version in `/.julia`, do I have to do this?

**Comment by stevengj** [comment]
You have to run `Pkg.build("PyCall")` if you want to change python via `ENV["PYTHON"]` ... rebuilding TensorFlow by itself is not sufficient.

If you do that, you should be able to use your existing Anaconda distribution, no need to force Julia to install its own.

**Comment by tkf** [comment]
If you want to have manual control for conda installation, see also: https://github.com/JuliaPy/Conda.jl#using-a-pre-existing-conda-installation

**Comment by daxinnan** [comment]
> You have to run `Pkg.build("PyCall")` if you want to change python via `ENV["PYTHON"]` ... rebuilding TensorFlow by itself is not sufficient.
> 
> If you do that, you should be able to use your existing Anaconda distribution, no need to force Julia to install its own.

Of course I actually did run `build PyCall`before rebuild TensorFlow, but it didn't work.

**Comment by ianw89** [comment]
@daxinnan did you ever figure this out? I seem to having a similar issue. Setting the ENV["PYTHON"] = "/Some/path/to/python" doesn't seem to change anything (Yes, I run Pkg.build("PyCall"). It always ends up back on the default conda version I don't want.

**Comment by stevengj** [comment]
What is the build output?

**Comment by daxinnan** [comment]
> @daxinnan did you ever figure this out? I seem to having a similar issue. Setting the ENV["PYTHON"] = "/Some/path/to/python" doesn't seem to change anything (Yes, I run Pkg.build("PyCall"). It always ends up back on the default conda version I don't want.

Now I run julia-1.1.0, and everything is ok.

**Comment by bwang12** [comment]
> > @daxinnan did you ever figure this out? I seem to having a similar issue. Setting the ENV["PYTHON"] = "/Some/path/to/python" doesn't seem to change anything (Yes, I run Pkg.build("PyCall"). It always ends up back on the default conda version I don't want.
> 
> Now I run julia-1.1.0, and everything is ok.

That is very odd. I am running version 1.1.1 and yet I am still running into the issue where the default Python is always the conda one downloaded by Julia. 

Not only that, I cannot seem to make the changes to the ENV permanent. Everytime I re-start Julia, the ENV gets reset. I should add that I am running Julia at work and I do not have admin rights to my work computer. Perhaps that could be the reason. 

But for now, seems like the only way forward is just to re-install everything I need to Julia's Python. 

If anyone else ever figured it out, I would really appreciate it if you could share your solution. Thx.

**Comment by daxinnan** [comment]
> > > @daxinnan did you ever figure this out? I seem to having a similar issue. Setting the ENV["PYTHON"] = "/Some/path/to/python" doesn't seem to change anything (Yes, I run Pkg.build("PyCall"). It always ends up back on the default conda version I don't want.
> > 
> > 
> > Now I run julia-1.1.0, and everything is ok.
> 
> That is very odd. I am running version 1.1.1 and yet I am still running into the issue where the default Python is always the conda one downloaded by Julia.
> 
> Not only that, I cannot seem to make the changes to the ENV permanent. Everytime I re-start Julia, the ENV gets reset. I should add that I am running Julia at work and I do not have admin rights to my work computer. Perhaps that could be the reason.
> 
> But for now, seems like the only way forward is just to re-install everything I need in Julia's Python.
> 
> If anyone else ever figured it out, I would really appreciate it if you could share your solution. Thx.


> > > @daxinnan did you ever figure this out? I seem to having a similar issue. Setting the ENV["PYTHON"] = "/Some/path/to/python" doesn't seem to change anything (Yes, I run Pkg.build("PyCall"). It always ends up back on the default conda version I don't want.
> > 
> > 
> > Now I run julia-1.1.0, and everything is ok.
> 
> That is very odd. I am running version 1.1.1 and yet I am still running into the issue where the default Python is always the conda one downloaded by Julia.
> 
> Not only that, I cannot seem to make the changes to the ENV permanent. Everytime I re-start Julia, the ENV gets reset. I should add that I am running Julia at work and I do not have admin rights to my work computer. Perhaps that could be the reason.
> 
> But for now, seems like the only way forward is just to re-install everything I need in Julia's Python.
> 
> If anyone else ever figured it out, I would really appreciate it if you could share your solution. Thx.

I guess you wanna your conda and python which are installed.
Maybe you should remove the Conda and PyCall and delete the `conda` file folder in `.julia`.
Then, [set environment](https://github.com/JuliaPy/Conda.jl#using-a-pre-existing-conda-installation) like `export CONDA_JL_HOME="/home/xxx/anaconda3"`,
and you can go to install `Conda` and `PyCall`.

**Comment by pnadon** [comment]
I h=was having this issue too, where I would change ENV["PYTHON"] and then run Pkg.build("PyCall"), and it wouldnt do anything. Simply exiting the Julia REPL and starting over fixed it for me.

**Comment by talk2sunil83** [comment]
Though it is closed but may be useful to some one 
1. in terminal 

 - a. which python
<anaconda/python path>
2. In Julia REPL execute

 - ENV["PYTHON"]="<anaconda/python path>"
 - using Pkg
 - Pkg.build("PyCall")

3.  Then "using PyCall"
