### ISSUE TITLE
Better Python eval/exec?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#599]
I think `py"..."` has two major limitations:

### No private namespace

As `py"..."` does not support passing namespace dictionaries, you are forced to use `__main__` all the time.  It means that `py"..."` cannot be used in any libraries without interfering with other libraries.  There are things which are easier to do in Python syntax.  Some special syntaxes like `async`/`await` are not supported in PyCall.  But if `eval`/`exec` can't be done in a private namespace, `py"..."` is not an option.

Of course, you can create a custom Python module and `pyimport` it after tweaking `sys.path`.  But this is rather cumbersome to prepare if you just want to define a few Python functions.

### Multi-line eval

Python expression can span multiple lines.  Following code does not return the array as one would expect.

```julia
py"[
    1,
    2,
    3,
]"
```

I suppose current Julia can't distinguish `py"..."` and `py"""..."""` since `_mstr` is gone?

### Ideas

Here are a few ideas to fix the problem:

1. Extend `py_str` by adding options?

    - `py"..."eval(globals, locals)`
    - `py"..."exec(globals, locals)`
    - The idea is to return a callable from `py"..."eval` and `py"..."exec`.

2. Bring back `pyeval` and add `pyexec`?

    - `pyeval(source, [globals, [locals]]; returntype=PyAny)`
    - `pyexec(source, [globals, [locals]])`

3. Add macros `@pyeval` and `@pyexec`?

    - Actually, I suggest to implement `pyeval` and `pyexec` as macors, to extract file name and line number and pass them to Python.  This way, Python stack trace can show the code in Julia source.
    - Also, interpolation mechanism can be used here.
    - Implementation: https://gist.github.com/tkf/93a6d76f5ca2aa15bae2b1b72b162db9

I also suggest to add a `@pyload` macro (or `pyload` function) which is equivalent to:

```julia
locals = PyDict{Symbol, PyObject}()
@pyexec("...", locals)
return locals
```

This way, defining helper Python functions can easily be done:

```julia
ns = @pyload("""
def f():
    ...

def g():
    ...
""")
ns[:f]()
ns[:g]()
```

A better option probably is to return a `types.SimpleNamespace` so that you can do `ns.f` instead of `ns[:f]` once `getproperty` is implemented.

**Comment by tkf** [comment]
Alternatively, we can have a mapping from Julia module to a Python dict like this:

```julia
# In __init__
pynamespaces = Dict(
    Main => maindict(),
)

# In macro py_str
globals = get!(PyDict{String, PyObject}, pynamespaces, __module__)
```
 A nice benefit is that you don't need `@pyload` for defining Python helpers. You can just do:

```julia
module MyModule
using PyCall

function function_using_helper()
    py"f"()  # Only MyModule can access py"f"
end

function __init__()
    py"""
    def f():
        ...
    """
end
end
```

It still needs some other mechanism for solving multi-line eval (e.g., use Python `ast`) but it seems that it's simpler to use than my other ideas.

**Comment by tkf** [comment]
My biggest concern here is the namespace.  How about `pynamespaces` approach?  I think it's orthogonal to #348.

**Comment by stevengj** [comment]
The `pynamespaces` approach seems reasonable to me.
