### ISSUE TITLE
Changed python modules do not reload automatically

### ISSUE THREAD

**Issue by MaxandreJ** [JuliaPy/PyCall.jl#611]
Hi,

I've added to the path a python file of my own using
```
pushfirst!(PyVector(pyimport("sys")["path"]), "<path_to_my_file>")
```
then imported the python module into Julia
```
<my_module_name> = pyimport("<my_module_name>")
```
and finally called a function defined by the module
```
<my_module_name>[:<my_function_name>](my_arguments...)
```
I got an error from the call, so I changed the definition of the function. But when I called 
```
<my_module_name>[:<my_function_name>](my_arguments...)
```
again, the error was still there. Reimporting the module wasn't enough either, I had to stop and restart Julia. It would be better if the python module was reloaded every time I changed it, or at least reimported it? I'm using Revise.jl in "automatic" mode if that's relevant.

I'm using PyCall v"1.18.5+" and Julia v1.0.1.

Best,
Max

**Comment by stevengj** [comment]
See https://support.enthought.com/hc/en-us/articles/204469240-Jupyter-IPython-After-editing-a-module-changes-are-not-effective-without-kernel-restart … just like in Python, you have to explicitly reload the module with `importlib.reload` (in Python 3, or `reload` in Python 2).  That is, do:
```jl
pyimport("importlib")["reload"]("<my_module_name>")
```

**Comment by MaxandreJ** [comment]
Thank you for your answer @stevengj and thank you for providing me with the solution !

**Comment by Datseris** [comment]
As a comment to anyone finding this on the latest version of PyCall, which has some syntax changes, the correct way to do it now is like this:
```julia
pypsd = pyimport("PSD")
pyimport("importlib")."reload"(pypsd)
```
