### ISSUE TITLE
Unable to convert pyobject pandas DF to Julia DF

### ISSUE THREAD

**Issue by versipellis** [JuliaPy/PyCall.jl#622]
```
test = convert(DataFrame, data)
MethodError: Cannot `convert` an object of type PyObject to an object of type DataFrame
```

I'm aware of the existence of Pandas.jl, but I've heard mention multiple times that the state of maintenance of that library leaves much to be desired, and I'm trying to keep the number of packages I have to bring in to a minimum.

**Comment by tkf** [comment]
Conversions between "data frame" formats is a non-trivial task.  There are a few frameworks in Julia ecosystem dedicated to this domain including [TableTraits.jl](http://www.david-anthoff.com/jl4ds/stable/tabletraits.html) which is supported by [Pandas.jl](https://github.com/JuliaPy/Pandas.jl/blob/3a1e8b9f33b8dacd06200a88e1d00391a54e71d9/src/tabletraits.jl#L8).  I think this is very domain-specific and out of scope of PyCall.jl.

**Comment by versipellis** [comment]
Is the any "best practice" way to extract the data from a Python Pandas dataframe to any sort of Julia object? Would TableTraits.jl be the way to go? I'm explicitly trying to avoid pandas.jl.

**Comment by tkf** [comment]
Not sure what's the best practice, but it's simple to use pandas only with PyCall if you can translate what you want to do with the "basic types" (Python builtin + Numpy array):

```julia
julia> using PyCall

julia> py"""
       import pandas
       """

julia> pydf = py"pandas.DataFrame"(Dict(
           :a => collect(1:10),
           :b => repeat(["a", "b"], outer=5),
       ));

julia> py"print"(pydf)
    a  b
0   1  a
1   2  b
2   3  a
3   4  b
4   5  a
5   6  b
6   7  a
7   8  b
8   9  a
9  10  b
```

**Comment by versipellis** [comment]
Hmm, okay. Not exactly what I was looking for, but thank you!

**Comment by benjaminshi02003220** [comment]
That is also what I'm looking for.... Waiting for the answer..

**Comment by gvarthi** [comment]
Any updates on this issue resolution? I am also facing the same issue.

**Comment by tkf** [comment]
As mentioned in the first comment, the best approach is https://github.com/JuliaPy/Pandas.jl
