### ISSUE TITLE
Time for a v0.7-only release with getproperty support?

### ISSUE THREAD

**Issue by oschulz** [JuliaPy/PyCall.jl#624]
I'd love to be able to use `o.method` via `getproperty` - I wonder, what's the roadmap for releasing a Julia v0.7+ only version of PyCall?

**Comment by stevengj** [comment]
Basically, now that my fall classes (which used Julia 0.6) are over, my plan is to drop 0.6 in PyCall over the next couple of weeks, at which point we can start the transition to getproperty.

Closing as further discussions can take place in #517

**Comment by oschulz** [comment]
Sounds great, thanks for the update, @stevengj !

**Comment by oschulz** [comment]
(Sorry, I somehow didn't see #517).
