### ISSUE TITLE
py"..." less performant than the deprecated pyeval("...")

### ISSUE THREAD

**Issue by marius311** [JuliaPy/PyCall.jl#650]
In my case, I'm calling `eval` on a string I receive over some channel. As far as I can tell, the correct way to eval this string which I don't know at compile time given the new setup is, 

```
@time @eval @py_str $(channel.receive())
  3.430887 seconds (10.51 M allocations: 175.082 MiB, 0.65% gc time)
```

In my case the string is a `repr` of a ~500x500 matrix so as you see, it takes a while. However, this used to be a bit faster and use much less memory with the old way of doing it, 

```
@time pyeval(channel.receive())
  1.250484 seconds (458.00 k allocations: 18.907 MiB, 1.40% gc time)
```

Is there a better way to do this where I get back the old performance? Thanks.

**Comment by marius311** [comment]
Sorry, forgot to add, I'm on Julia 1.1.0, Python 3.6.7, and PyCall e137bb0 (current master).

**Comment by tkf** [comment]
Did you try double-`$` like `py"$$(channel.receive())"`?

```julia
julia> x = "[1,2,3]"
"[1,2,3]"

julia> py"""
       print(repr($x))
       """
'[1,2,3]'

julia> py"""
       print(repr($$x))
       """
[1, 2, 3]
```

**Comment by marius311** [comment]
Ah I didn't know about the double-`$`, thanks. I think that fixes it. Here's a self-contained benchmark (couldn't figure out how to do the interpolation right with BenchmarkTools, so hopefully nothing weird introduced by hand below):

```julia
julia> using PyCall

julia> py"""
       import numpy as np
       """

julia> repr = py"repr(np.random.rand(100,100).tolist())";

julia> @time for i=1:10
           @eval @py_str $repr
       end
  1.291032 seconds (7.06 M allocations: 137.216 MiB, 1.68% gc time)

julia> @time for i=1:10
           py"$$repr"
       end
  0.292742 seconds (304.20 k allocations: 8.109 MiB)
```

Closing as I doubt there's any issue with PyCall here.
