### ISSUE TITLE
Difference in result between pandas operation in python3 direct and python3 via Julia PyCall

### ISSUE THREAD

**Issue by dnk8n** [JuliaPy/PyCall.jl#652]
**Python3 direct**

```
import pandas as pd

ids = ["id1", "id2", "id3"]
seqs = ["ABC", "ABCDE", "ABCD"]

df = pd.DataFrame(
    {
        "sequence": seqs,
    },
    index=ids
)
df
```

**Python3 via Julia PyCall**

```
using PyCall
@pyimport pandas as pd

ids = ["id1", "id2", "id3"]
seqs = ["ABC", "ABCDE", "ABCD"]

df = pd.DataFrame(
    Dict(
        :sequence => seqs
    ),
    index=ids
)
df
```

At this point both outputs look identical:
```
	sequence
id1	ABC
id2	ABCDE
id3	ABCD
```
Now, I continue to do the same in each, but get different results

**Python3 direct**

```
df["sequence_length"]  = df["sequence"].str.len()
df
```
Output:
```
	sequence	sequence_length
id1	ABC		3
id2	ABCDE		5
id3	ABCD		4
```
**Python3 via Julia PyCall**

```
df["sequence_length"]  = df["sequence"][:str][:len]()
df
```
Output:
```
	sequence
id1	ABC
id2	ABCDE
id3	ABCD
```

**Comment by dnk8n** [comment]
Interestingly if I do the following in both:

```
df["sequence_length"]
```

I get, outputs:
**Python3 via Julia PyCall**
```
PyObject id1    3
id2    5
id3    4
Name: sequence, dtype: int64
```

**Python3 direct**
```
id1    3
id2    5
id3    4
Name: sequence_length, dtype: int64
```


And if I do the following in both:

```
df[["sequence_length"]]
```

I get, outputs:
**Python3 via Julia PyCall**
```
MethodError: no method matching getindex(::PyCall.PyObject, ::Array{String,1})

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
 [2] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/jovyan/.julia/v0.6/IJulia/src/execute_request.jl:193
 [3] (::Compat.#inner#6{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/jovyan/.julia/v0.6/Compat/src/Compat.jl:186
 [4] eventloop(::ZMQ.Socket) at /home/jovyan/.julia/v0.6/IJulia/src/eventloop.jl:8
 [5] (::IJulia.##13#16)() at ./task.jl:335

```

**Python3 direct**
```
	sequence_length
id1	3
id2	5
id3	4
```

**Comment by stevengj** [comment]
` df["sequence"][:str][:len]()` is probably converting to native Julia objects at some point and losing the extra meta-information that Python dataframes store.  If you want to keep native Python objects, do ` pycall(df["sequence"]["str"]["len"], PyObject)` instead.

**Comment by dnk8n** [comment]
@stevengj I don't quite follow.

```df["sequence_length"] = pycall(df["sequence"]["str"]["len"], PyObject)```

results in the same behaviour as described in the issue.

Please explain why this is not an issue with PyCall? I expected to be able to work with Python libraries in Julia. Pandas is quite a popular library with its apply function being one of the more popular functions.

I tried looking at https://github.com/JuliaPy/Pandas.jl but had even less success.

Is there an alternate recommendation on working with Pandas in Julia? One of the pros I saw with Julia was the fact that it could inherit from Python... but this doesn't seem to be very straightforward.

**Comment by dnk8n** [comment]
That said, I found a workaround which I am happy enough with:

```
using PyCall
py"""
import pandas as pd

def df_with_seq_len():
    ids = ['id1', 'id2', 'id3']
    seqs = ['ABC', 'ABCDE', 'ABCD']

    df = pd.DataFrame(
        {
            'sequence': seqs,
        },
        index=ids
    )
    df['sequence_length']  = df['sequence'].str.len()
    return df
"""
```

```
df = py"df_with_seq_len"()
df
```
