### ISSUE TITLE
Error caused by system libraries being older than python libraries

### ISSUE THREAD

**Issue by cjdoris** [JuliaPy/PyCall.jl#659]
Here is a curious thing.

On my (linux) system, if I do `pyimport("scipy.interpolate")` then I get an error caused by my system version of `libstdc++.so` being older than the one installed with `python`.

The reason this happens is that the `DT_RPATH` attribute of `python` is set to `$ORIGIN/../lib`, which resolves to `/my/anaconda/path/lib` and that for `julia` is set to `$ORIGIN/../lib64` which resolves to `/usr/lib64` (see [man ld.so](http://man7.org/linux/man-pages/man8/ld.so.8.html) for what this means). Anaconda ships with a newer version of `libstdc++.so` than is installed on my system, and `scipy.interpolate` expects this newer version. Therefore all is ok when running in `python`, but using `PyCall` in `julia` the older version gets loaded.

There are two solutions which fix this from "outside" `PyCall`:
- With root priveleges: update `/usr/lib64/libstdc++.so`.
- Without root priveleges: copy the `julia` executable to somewhere like `~/julialocal/bin/julia` and make symlinks to `libjulia.so` and `libstdc++.so` in `~/julialocal/lib64`.

I wonder if it is possible to get `PyCall` to somehow intercept calls to `dlopen(lib,flags)` from `libpython` and to change `lib` to the absolute path that would have been used from `python`?

**Comment by stevengj** [comment]
The C++ standard library has already been loaded by `julia` before PyCall loads, since Julia’s implementation uses C++ to call LLVM. So there is no way for PyCall to change this library’s path.
