### ISSUE TITLE
Suspicious segfault since #668

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyCall.jl#670]
We thought the segmentation faults in #668's CI were some temporary bug in Julia nightly.  However, I just noticed that it happens with Julia 1.0.3 as well:

```
signal (11): Segmentation fault
in expression starting at /home/travis/build/JuliaPy/PyCall.jl/test/runtests.jl:29
_ZNK4llvm4Type18isSizedDerivedTypeEPNS_15SmallPtrSetImplIPS0_EE at /home/travis/julia/bin/../lib/julia/libLLVM-6.0.so (unknown line)
_ZN4llvm12InstCombiner12visitBitCastERNS_11BitCastInstE at /home/travis/julia/bin/../lib/julia/libLLVM-6.0.so (unknown line)
...
```

--- https://travis-ci.org/JuliaPy/PyCall.jl/jobs/510151180#L804 from `v1.91.0` tag
(also https://travis-ci.org/JuliaPy/PyCall.jl/jobs/510149760#L793 from `master` branch)

**Comment by stevengj** [comment]
Those errors went away in #668 after I added a `GC.@protect` in the `PyArray{PyPtr} -> Array{PyObject}` conversion, IIRC?

**Comment by tkf** [comment]
The CI results I linked above are from the build for `v1.91.0` and `master`.  Both for the commit 33f07ebd6ad3d8b911a3447fadf48b08cceaa9b7.

**Comment by stevengj** [comment]
I committed your workaround from JuliaLang/julia#31473

**Comment by stevengj** [comment]
Tagged 1.91.1 with fix.
