### ISSUE TITLE
Array{Float64,0} returned from scipy

### ISSUE THREAD

**Issue by sitnarf** [JuliaPy/PyCall.jl#680]
Hi,
I am new to Julia, but I think, this is bad. Check this out:
```julia
interp = pyimport("scipy.interpolate")
np = pyimport("numpy")
x = np.arange(0, 10)
y = np.exp(-xx/3.0)
f = interp.interp1d(x, y)
println(f(1))
#prints 0.716531
```

So far so good. But, why this happens?
```julia
println([f(1), f(2), f(3)])
println(f.(x))
# Both prints
# Array{Float64,0}[0.716531, 0.513417, 0.367879]
# Array{Float64,0}[1.0, 0.716531, 0.513417, 0.367879, 0.263597, 0.188876, 0.135335, 0.096972, 0.0694835, 0.0497871]
```

Versions:
```
PyCall: 1.91.1
Julia: 1.1.0
Scipy: 1.2.1
```

**Comment by coroa** [comment]
Well, it's a faithful representation of the Python's `interp1d` return value.

The function `f` expects to be called on an array and thus interprets `f(1)` as in `f(np.array(1))`, a 0-dim numpy array, and then returns the interpolation as such. Just note the type of your construct

```julia
julia> typeof(f.(x))
Array{Array{Float64,0},1}
```

To interpolate at points 1, 2 and 3, you should use,
```julia
julia> f([1,2,3])
3-element Array{Float64,1}:
 0.7165313105737893 
 0.513417119032592  
 0.36787944117144233
```
instead.

**Comment by sitnarf** [comment]
Thanks!
