### ISSUE TITLE
Making PyCall for os.urandom results in "base64 binary data"

### ISSUE THREAD

**Issue by FinlayDaG33k** [JuliaPy/PyCall.jl#685]
Hii there,

I'm trying to get the `os.urandom` method from Python to work in my Julia script.  
However, all I can get from it is a base64 binary data:
```
salt = os.urandom(floor(Int, salt_length / 2));
println(salt);
```

> base64 binary data: 2pzXfwq2qPAOCg==

I wonder if this is a bug or intended behaviour and how one could fix this as it's nowhere in the documentation.

**Comment by FinlayDaG33k** [comment]
Found that I can do this using the the Julia Random library instead...
Closing

**Comment by stevengj** [comment]
It works fine for me, though it is returning a `String` which is probably not what you want in Julia.  If you want a `Vector{UInt8}` (i.e. a vector of bytes), you can do:
```jl
julia> pycall(pyimport("os").urandom, Vector{UInt8}, 10)
10-element Array{UInt8,1}:
 0xeb
 0x4b
 0x12
 0x69
 0xf6
 0x78
 0x56
 0x22
 0x7a
 0x8b
```
