### ISSUE TITLE
Which environment (as in environment variables) does PyCall use?

### ISSUE THREAD

**Issue by goretkin** [JuliaPy/PyCall.jl#698]
I can set an environment variable as follows:

`PyCall.PyDict(PyCall.pyimport("os").environ)["SOURCE_DATE_EPOCH"] = "0"`

Using `ENV` in Julia did not work. I would like to understand which environment the python interpreter is in. As far as I understand, there isn't a separate process for the interpreter, so I am surprised there is a separate environment.

**Comment by stevengj** [comment]
See [the Python docs for `os.environ`](https://docs.python.org/2/library/os.html#process-parameters):

> This mapping is captured the first time the os module is imported, typically during Python startup as part of processing `site.py`. **Changes to the environment made after this time are not reflected** in `os.environ`, except for changes made by modifying `os.environ` directly.

**Comment by goretkin** [comment]
Ah, thanks for the explanation. So this is specific to how python handles environment variables. Unintuitive, but certainly documented.
