### ISSUE TITLE
Null PyObject error when installing package that uses PyCall using Pkg

### ISSUE THREAD

**Issue by ethanwhite** [JuliaPy/PyCall.jl#699]
First - thanks for this awesome package. We're using it to wrap our Python software for use in Julia.

I'm currently seeing an error message when calling functions that use PyCall after installing the package (into Julia 1.1.1) using `Pkg`, but everything works fine if the package is loaded locally using `include` or if the commands that trigger the error are called directly.

### Install Python package
```bash
$ pip install retriever
```

or

```bash
$ conda install -c conda-forge retriever
```

### Manually running command works

```julia
using PyCall
rt = pyimport("retriever")
PyObject <module 'retriever' from '/usr/local/lib/python3.6/dist-packages/retriever-2.4.0-py3.6.egg/retriever/__init__.py'>
rt.check_for_updates()
Downloading scripts: 100%|███████████████| 103/103 [00:00<00:00, 2098.11files/s]
```

### Installing using Pkg and running the wrapper function errors

```julia
julia> Pkg.add(PackageSpec(url="https://github.com/ethanwhite/Retriever.jl", rev="julia1pt0"))
julia> using Retriever
julia> Retriever.check_for_updates()

ERROR: ArgumentError: ref of NULL PyObject
Stacktrace:
 [1] getproperty(::PyObject, ::String) at /home/ethan/.julia/packages/PyCall/ttONZ/src/PyCall.jl:303
 [2] getproperty(::PyObject, ::Symbol) at /home/ethan/.julia/packages/PyCall/ttONZ/src/PyCall.jl:313
 [3] check_for_updates() at /home/ethan/.julia/packages/Retriever/4if63/src/Retriever.jl:20
 [4] top-level scope at none:0
```

Link to code for `Retriever.check_for_updates()`: https://github.com/ethanwhite/Retriever.jl/blob/julia1pt0/src/Retriever.jl#L17

I'm new to Julia development, so apologies if this is something obvious. Any help pointing me in the right direction (or to a more appropriate place to ask this question) would certainly be appreciated.

**Comment by tkf** [comment]
The problem is https://github.com/ethanwhite/Retriever.jl/blob/9505041281f8113f8e49b3f7dd2d6cc0e6599700/src/Retriever.jl#L10

You need to use `copy!` (see https://github.com/JuliaPy/PyCall.jl#using-pycall-from-julia-modules) or `py""` (see https://github.com/JuliaPy/PyCall.jl#usage)

**Comment by ethanwhite** [comment]
Thanks @tkf! That fixed it. I had read that chunk of the docs and been confused by the precompiled aspect of things, but thanks to you I've read up more now and understand everything. Really appreciate it.
