### ISSUE TITLE
PyCall build errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by macd** [JuliaPy/PyCall.jl#708]
I don't think this is related to #704, but I cannot build PyCall
on Ubuntu 18.04 with master julia and master PyCall, but there does exist a hack to fix.
Also, I am using Conda.jl with `CONDA_JL_HOME=/home/macd/anaconda3/envs/conda_jl`,
which does successfully build.

First the error:

```
(v1.4) pkg> build PyCall
  Building Conda ─→ `~/julia-versions/dot_julia-1.4/packages/Conda/kLXeC/deps/build.log`
  Building PyCall → `~/jlang/dev/PyCall.jl/deps/build.log`
 Resolving package versions...
┌ Error: Error building `PyCall`: 
│ Collecting package metadata (current_repodata.json): ...working... done
│ Solving environment: ...working... done
│ 
│ # All requested packages already installed.
│ 
│   File "<string>", line 1
│     import sys; print(sys.executable
│                                    ^
│ SyntaxError: unexpected EOF while parsing
│ ┌ Info: No system-wide Python was found; got the following error:
│ │ MethodError(adjoint, ("get_config_var('VERSION)",), 0x0000000000006892)
│ └ using the Python distribution in the Conda package
│ [ Info: Running `conda install -y numpy` in root environment
...
```

The 'fix' is to escape a right parens, ie the following line in buildutils.jl

```
pyvar(python::AbstractString, mod::AbstractString, var::AbstractString) = chomp(read(pythonenv(`$python -c "import $mod; print($mod.$var)"`), String))
```

must be changed to

```
pyvar(python::AbstractString, mod::AbstractString, var::AbstractString) = chomp(read(pythonenv(`$python -c "import $mod; print($mod.$var\)"`), String))
```

Notice the escape on the right parens on `print($mod.$var\)`

Did not do a PR, since this is obviously not the correct fix, but
a hack to work around an interpolation problem somewhere else.

**Comment by chriselrod** [comment]
I have the same problem on Clear Linux.

**Comment by tkf** [comment]
See https://github.com/JuliaLang/julia/pull/32948 and https://github.com/JuliaLang/julia/pull/32408#issuecomment-522168938
