### ISSUE TITLE
Using matplotlib.tri without PyPlot

### ISSUE THREAD

**Issue by henry2004y** [JuliaPy/PyCall.jl#728]
Hi,

The unstructured triangular grid functions can be found with
```Julia
using PyPlot
X, Y = rand(10), rand(10)
triang = matplotlib.tri.Triangulation(X,Y)
```

However, when I tried to import matplotlib directly using PyCall:
```Julia
using PyCall
matplotlib = pyimport("matplotlib")
X, Y = rand(10), rand(10)
triang = matplotlib.tri.Triangulation(X,Y)
```
It showed:
```
ERROR: KeyError: key "tri" not found
```

Why is that? What is the difference here?

**Comment by stevengj** [comment]
The same thing happens in Python
```py
>>> import matplotlib
>>> matplotlib.tri
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'matplotlib' has no attribute 'tri'
```
I think that the `tri` module must be imported dynamically at some point during Matplotlib's initialization, so that it isn't available if you simply import the module.

Easy fix:
```jl
tri = pyimport("matplotlib.tri")

X, Y = rand(10), rand(10)
triang = tri.Triangulation(X,Y)
```
