### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by isentropic** [JuliaPy/PyCall.jl#732]
Currently, PyCall can't compile itself with python3.8.
I think most of the users don't need the functinality of 3.8, but just the ability to run matplotlib and such.
```
julia> using PyCall
[ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
ERROR: LoadError: LoadError: could not load library "/usr/lib/libpython3.7m.so.1.0"
/usr/lib/libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by isentropic** [comment]
This could be a workaround for some:
```
 sudo ln -s /usr/lib/libpython3.8.so.1.0 /usr/lib/libpython3.7m.so.1.0
```
or according link

**Comment by stevengj** [comment]
I've used PyCall with Python 3.8 with no problem.    If you install a new Python version you need to re-run `build PyCall`.
