### ISSUE TITLE
Using Julia MKL build with numpy (related to #443)

### ISSUE THREAD

**Issue by kumarbal** [JuliaPy/PyCall.jl#766]
Is it possible to have a build of JuliaPro-1.4.1 that is designed to integrate with numpy without losing MKL compatibility. I know we can choose to rebuild Julia as a solution, but it would be good if there were a pre-built binary available.

This is related to https://github.com/JuliaPy/PyCall.jl/issues/443

**Comment by stevengj** [comment]
Not easily.   You would need either the 32-bit (LP64) version of MKL in Julia (which doesn't seem supported by MKL.jl, but it is possible to recompile Julia to use this I believe), or an ILP64 version of Numpy (which doesn't exist, I believe).
