### ISSUE TITLE
Versions of python packages with non-standard version numbers

### ISSUE THREAD

**Issue by ablaom** [JuliaPy/PyCall.jl#773]
Please see https://github.com/cstjean/ScikitLearn.jl/issues/67

This has popped up more than once (slack discussion). Perhaps a slightly more informative error message is all that's required. One user eventually resolved his problem but without realising what the real issue was, which may have delayed resolution.

**Comment by tkf** [comment]
FYI 0.22.2.post1 mentioned in the issue is a valid version number according to [PEP 440 specification](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers).  You can use VersionParsing (like PyCall does) to parse it.

**Comment by ablaom** [comment]
Thanks for that. So is the claim here not correct:https://github.com/cstjean/ScikitLearn.jl/issues/67#issuecomment-598545792 ?

**Comment by tkf** [comment]
I don't think there is anything "incorrect" in that comment. It's just that PEP 440 and SemVer are different versioning format. What is wrong is that expecting all Python packages to use SemVer (not all of them do).

**Comment by stevengj** [comment]
As I commented on the other issue, ScikitLearn.jl should use https://github.com/stevengj/VersionParsing.jl to parse version numbers of Python packages.
