### ISSUE TITLE
Can't use PyCall in a testset when imported in the test set

### ISSUE THREAD

**Issue by kcajf** [JuliaPy/PyCall.jl#774]
Met with this odd issue today. I was trying to use PyCall in a unit test, to check some julia code against existing python code. PyCall has been added to MyPackage/test/Project.toml.

Here are three variations of `MyPackage/test/runtests.jl`:

Works:
```
using Test, MyPackage

using PyCall
Test.@testset "asdf" begin
    py"""666"""
end
```

Also works:
```
using Test, MyPackage

Test.@testset "asdf" begin
    using PyCall
end
```

Doesn't work:
```
using Test, MyPackage

Test.@testset "asdf" begin
    using PyCall
    py"""666"""
end
```
```
ERROR: LoadError: LoadError: UndefVarError: @py_str not defined
```

This doesn't seem to be a general limitation around external imports - replacing `PyCall` with `Dates` and `py"""666"""` with `Date(2018, 1, 1)` works in all three cases, for example.

I haven't used `Test` much generally, so maybe there is something very obvious going on here.

**Comment by tkf** [comment]
`py"""666"""` is a macro call. Evaluating it requires `using PyCall` before the top-level expression that includes this macro call. In general, it's always better to write `using PyCall` in top-level scope, preferably beginning of the file.

**Comment by kcajf** [comment]
Thanks @tkf , that's good to know.
