### ISSUE TITLE
Autoreload

### ISSUE THREAD

**Issue by mileslucas** [JuliaPy/PyCall.jl#775]
This is a **feature request**

I've recently been doing a lot of coding two packages in Julia and python side-by-side and have been sorely missing the `%autoreload 2` magic from ipython. Is this something that can be incorporated into PyCall? The ideal usage I could image is something like
```julia
using PyCall
autoreload()
```

**Comment by stevengj** [comment]
I think you could use IPython itself for this, at least from IJulia.  Something like:
```jl
autoreload = pyimport("IPython.extensions.autoreload").AutoreloadMagics()
IJulia.push_preexecute_hook(() -> autoreload.pre_run_cell())
IJulia.push_postexecute_hook(() -> autoreload.post_execute_hook())
```

**Comment by mileslucas** [comment]
I'll give that a try! I'm curious, though, if we can get the same functionality for use on the command line too. Our REPL is much closer to ipython REPL than the python REPL, so if we can make it work without _having_ to use IJulia, that would be awesome!

**Comment by stevengj** [comment]
Yes, in Julia 1.5 you can use the new REPL AST transformation feature to push a transformation that calls the pre/post execute hooks before the code that is executed.

This is very similar to what Revise.jl does.  See https://github.com/timholy/Revise.jl/pull/425

**Comment by stevengj** [comment]
If you get this to work, I would suggest putting it in a `PyRevise.jl` package (analogous to Revise.jl).

**Comment by mileslucas** [comment]
Sounds good! I'll go ahead and close this considering your point about the auxiliary package. Thanks!
