### ISSUE TITLE
issues with other packages loading binary files

### ISSUE THREAD

**Issue by ppalmes** [JuliaPy/PyCall.jl#784]
running scikitlearn functions fail when run together with arpack.jl and xgboost.jl with packages loading binary files. is there any way to avoid conflict of other packages loading binaries?

**Comment by ppalmes** [comment]
fixed it by placing them inside ```function __init()```. i think packages with binaries loaded should have warnings if they are not enclosed inside init function because the error of conflict is not easy to debug and does not reflect to the real issue.

**Comment by stevengj** [comment]
The most general way to avoid shared-library conflicts (with packages loading incompatible versions of libraries that define the same symbols) is to have those packages build custom binaries that prefix symbols with some unique prefix, like Julia does with OpenBLAS.

I don't think there is any way for PyCall to automatically detect Python packages that load external libraries.
