### ISSUE TITLE
Anaconda3 not supporting PyCall

### ISSUE THREAD

**Issue by sasi591** [JuliaPy/PyCall.jl#804]
```jl
julia> np = pyimport("numpy")
ERROR: PyError (PyImport_ImportModule

The Python package Pandas could not be found by pyimport. Usually this means
that you did not install Pandas in the Python version being used by PyCall.

PyCall is currently configured to use the Python version at:

C:\ProgramData\Anaconda3\python.exe

and you should use whatever mechanism you usually use (apt-get, pip, conda,
etcetera) to install the Python package containing the Pandas module.

One alternative is to re-configure PyCall to use a different Python
version on your system: set ENV["PYTHON"] to the path/name of the python
executable you want to use, run Pkg.build("PyCall"), and re-launch Julia.

Another alternative is to configure PyCall to use a Julia-specific Python
distribution via the Conda.jl package (which installs a private Anaconda
Python distribution), which has the advantage that packages can be installed
and kept up-to-date via Julia.  As explained in the PyCall documentation,
set ENV["PYTHON"]="", run Pkg.build("PyCall"), and re-launch Julia. Then,
To install the Pandas module, you can use `pyimport_conda("Pandas", PKG)`,
where PKG is the Anaconda package the contains the module Pandas,
or alternatively you can use the Conda package directly (via
`using Conda` followed by `Conda.add` etcetera).

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'Pandas'")

Stacktrace:
 [1] pyimport(::String) at C:\Users\Sasank Tammireddy\.julia\packages\PyCall\zqDXB\src\PyCall.jl:536
 [2] top-level scope at REPL[4]:1
```

**Comment by sasi591** [comment]
I have just installed PyCall and changed my ENV to C:\ProgramData\Anaconda3\python.exe . Then I just pyimport panda. It throws error. Its happening not only for pandas numpy, others too. Can some one help me out quickly

**Comment by stevengj** [comment]
To be clear, you should do:
```jl
julia> ENV["PYTHON"] = raw"C:\ProgramData\Anaconda3\python.exe"

pkg> build PyCall
```
and then restart Julia before doing `using PyCall`.

**Comment by sasi591** [comment]
Hello Sir,
All the above process is already done before it.

**Comment by sasi591** [comment]
Sir, Thank you for your quick reply but as you can see PyCall is already using

PyCall is currently configured to use the Python version at:

C:\ProgramData\Anaconda3\python.exe

**Comment by sasi591** [comment]
<class 'ImportError'>
ImportError('\n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from "C:\\Users\\Sasank Tammireddy\\AppData\\Local\\Programs\\Julia 1.5.0\\bin\\julia.exe"\n  * The NumPy version is: "1.19.1"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.\n')
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)

**Comment by sasi591** [comment]
Above is the Importing Error

**Comment by stevengj** [comment]
Did you resole the problem?

**Comment by sasi591** [comment]
Yeah I have resolved the issue. I am extremely sorry to bother you. The
fault is that the installation of anaconda has few error in my PC.

So for above reason PyCall couldn't imported numpy. Once again I am very
thankful to you for your responses and support.

Thanks & Regards

---
Yours faithfully,
Sasank

**Comment by zhaoq2015** [comment]
Hi, I'm facing the same problem. How did you solve it? Any suggestions will be helpful.
