### ISSUE TITLE
How to avoid having to restart session after changing python script?

### ISSUE THREAD

**Issue by ym-han** [JuliaPy/PyCall.jl#807]
Hi there,

Apologies for the neophyte question, but --- is there a way to reload python scripts that we're importing with pycall without having to restart the julia session? I've been trying pycall out on a remote machine, and I seem to need to restart the session every time I change the python script, even when I'm using Revise.jl. (though perhaps the remote environment thing is getting in the way of Revise's doing its magic?)

Another hack-y method that just occurred to me is copying and pasting the python script over to the julia file and making whatever changes I need in the julia file, though I haven't tried that yet. (I would really prefer not to have to do that though.)

Thanks in advance!

**Comment by samuela** [comment]
Does
```julia
importlib = pyimport("importlib")
yourmodule = pyimport("yourmodule")
importlib.reload(yourmodule)
```
work for you?

**Comment by ym-han** [comment]
Thanks samuela! :)
