### ISSUE TITLE
PkgEval: find_libpython test failures with PYTHON=""

### ISSUE THREAD

**Issue by maleadt** [JuliaPy/PyCall.jl#812]
In https://github.com/JuliaComputing/NewPkgEval.jl/pull/74 we switched PkgEval to setting `PYTHON=""`, but that causes test failures:

```
DEBUG is_windows = False
DEBUG is_apple = False
DEBUG Candidate: /home/pkgeval/.julia/packages/PyCall/zqDXB/test/python
DEBUG Not found.
DEBUG Candidate: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
DEBUG Not found.
DEBUG Candidate: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.so
DEBUG Not found.
DEBUG Candidate: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython.so
DEBUG Not found.
DEBUG Candidate: ../libpython2.7.so
DEBUG Not found.
DEBUG Candidate: ../libpython2.so
DEBUG Not found.
DEBUG Candidate: ../libpython.so
DEBUG Not found.
DEBUG Candidate: /usr/lib/libpython2.7.so
DEBUG Not found.
DEBUG Candidate: /usr/lib/libpython2.so
DEBUG Not found.
DEBUG Candidate: /usr/lib/libpython.so
DEBUG Not found.
DEBUG Candidate: /usr/libpython2.7.so
DEBUG Not found.
DEBUG Candidate: /usr/libpython2.so
DEBUG Not found.
DEBUG Candidate: /usr/libpython.so
DEBUG Not found.
DEBUG Candidate: None
DEBUG Not found.
dlopen(libpython2.7) ==> ErrorException("could not load library \"libpython2.7\"\nlibpython2.7.so: cannot open shared object file: No such file or directory")
dlopen(libpython2) ==> ErrorException("could not load library \"libpython2\"\nlibpython2.so: cannot open shared object file: No such file or directory")
dlopen(libpython) ==> ErrorException("could not load library \"libpython\"\nlibpython.so: cannot open shared object file: No such file or directory")
find_libpython: Error During Test at /home/pkgeval/.julia/packages/PyCall/zqDXB/test/test_build.jl:13
  Test threw exception
  Expression: isfile((find_libpython(python))[2])
  Couldn't find libpython; check your PYTHON environment variable.
  
  The python executable we tried was python (= version 2.7).
  Re-building with
      ENV["PYCALL_DEBUG_BUILD"] = "yes"
  may provide extra information for why it failed.
  
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] find_libpython(::String; _dlopen::typeof(Libdl.dlopen)) at /home/pkgeval/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:72
   [3] find_libpython(::String) at /home/pkgeval/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:41
   [4] top-level scope at /home/pkgeval/.julia/packages/PyCall/zqDXB/test/test_build.jl:13
   [5] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115
   [6] top-level scope at /home/pkgeval/.julia/packages/PyCall/zqDXB/test/test_build.jl:9

Test Summary:  | Pass  Error  Total
find_libpython |    6      2      8
```

Even though it did successfully install a Python distribution:

```
┌ Info: Python version 3.8.3 from /home/pkgeval/.julia/conda/3/lib/libpython3.8.so.1.0, PYTHONHOME=/home/pkgeval/.julia/conda/3:/home/pkgeval/.julia/conda/3
│ ENV[PYTHONPATH]=
│ ENV[PYTHONHOME]=
└ ENV[PYTHONEXECUTABLE]=
```

**Comment by stevengj** [comment]
@tkf, any ideas?

**Comment by stevengj** [comment]
That is, `find_libpython` is working when we run `Pkg.build("PyCall")`, but it is failing in [`test_build.jl`](https://github.com/JuliaPy/PyCall.jl/blob/master/test/test_build.jl#L8).

**Comment by stevengj** [comment]
Hmm, I'm not sure we should be running this test in `test_build.jl` — it is making sure that the `find_libpython` script works with the system `python` even if we don't need it.  It seems like this may fail if `python` is statically linked, for example?

**Comment by stevengj** [comment]
Maybe we should just comment out [this line](https://github.com/JuliaPy/PyCall.jl/blob/c411ea065a6d422d0e52430a08f1b988b86b87dd/test/runtests.jl#L790).

If someone wants to run the `find_libpython` tests for all of the `python` executables on their system, they should probably run `test_build.jl` manually.

**Comment by tkf** [comment]
I think it's OK to not run `test_build.jl` via `runtests.jl` as long as we run it in our CI (opt-in).  Or skip it in PkgEval by checking `if lowercase(get(ENV, "JULIA_PKGEVAL", "false")) == "true"` or something (opt-out).

I think it'd be better to get reports from users who find errors in `test_build.jl`.  For example, [the test failure](https://github.com/JuliaCI/NanosoldierReports/blob/182f1605550d605a38092a8e980c595ff8982b5a/pkgeval/by_date/2020-08/26/logs/PyCall/1.6.0-DEV-5da96913c2.log#L101-L113) motivated https://github.com/JuliaComputing/NewPkgEval.jl/pull/74 actually should have been reported in PyCall so that we can, in principle, investigate and document the case building PyCall does not work.

I'm OK either way (opt-in/opt-out) though.
