### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPy/PyCall.jl#822]
The faster startup code, already in in master, is effective.

I tried newer options, and couldn't get a better startup however with any combinations:
https://github.com/JuliaLang/julia/pull/37041/files

The code already in should probably also go into PyPlot.jl

**Comment by PallHaraldsson** [comment]
Also useful to tag for new features it seems (breaking change, so what version number?):

https://github.com/JuliaPy/PyCall.jl/pull/792

**Comment by DilumAluthge** [comment]
@stevengj What do you think about tagging a new release of PyCall.jl?

**Comment by tkf** [comment]
@stevengj Do you mind if I release v1.92.0 #840?
