### ISSUE TITLE
Using the scikitlearn libs thru pycall is not thread-safe

### ISSUE THREAD

**Issue by ppalmes** [JuliaPy/PyCall.jl#852]

**Comment by stevengj** [comment]
Calling Python is not thread safe; I don't think there is anything we can do about this…

**Comment by stevengj** [comment]
(We'd have to wrap every call to Python with PyEval_AcquireLock and PyEval_ReleaseLock, which doesn't seem practical…)

**Comment by tk3369** [comment]
So more practically, a user can do that manually for specific python calls?
