### ISSUE TITLE
Is there a way to pass a Python ctypes pointer to Julia then use it in a ccall? 

### ISSUE THREAD

**Issue by marius311** [JuliaPy/PyCall.jl#868]
Basically I have some Python code which uses ctypes to wrap some Fortran structs, and on the Python side I can do a `byref(some_wrapped_object)` to get a pointer which I can then pass as an argument to some Fortran calls. Is there a way to pass the pointer to Julia then use that in a `ccall` instead? The object looks like:

```python
In [1]: byref(some_wrapped_object)                                                                                                                  
Out[1]: <cparam 'P' (0x55a0ec981d80)>
```

**Comment by stevengj** [comment]
Use `ctypes.cast` to get a `c_void_p`, which PyCall knows to convert to a pointer.  For example:
```jl
julia> ctypes = pyimport("ctypes");

julia> o = ctypes.byref(pycall(ctypes.c_int, PyObject, 3))
PyObject <cparam 'P' (0x7fa9929a3910)>

julia> ctypes.cast(o, ctypes.c_void_p)
Ptr{Nothing} @0x00007fa9929a3910
```

**Comment by marius311** [comment]
Beautiful, thank you!
