### ISSUE TITLE
Need manual deletion of prefs to trigger a proper re-build

### ISSUE THREAD

**Issue by Moelf** [JuliaPy/PyCall.jl#870]
As the title says. Even when deleting `deps.jl`, if the `.julia/prefs/PyCall` hasn't changed, `]build` will still proceed to build against the original python env.

Probably should add a check, if `ENV` doesn't match `prefs`, update both `prefs` and `deps.jl`

**Comment by stevengj** [comment]
I don't follow you.  The `PYTHON` environment variable [already takes precedence over the prefs file](https://github.com/JuliaPy/PyCall.jl/blob/bbe4efc9aca2f80eb500a2cb99d5a469ab6886e4/deps/build.jl#L45), no?

**Comment by Moelf** [comment]
indeed that is the case, currently running into a bug that only exists in job submission container so it's a bit hard to debug sorry for the noise.

The goal is trying to relocate `~./julia` and a Conda virtual environment in tarball and ship into the job executing environment, but for some reason, PyCall is not re-building properly.
