### ISSUE TITLE
_apply_latest removed on Julia master

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaPy/PyCall.jl#873]
This PR: https://github.com/JuliaLang/julia/pull/38835 removed the `_apply_latest` builtin used by PyCall here: https://github.com/JuliaPy/PyCall.jl/blob/bbe4efc9aca2f80eb500a2cb99d5a469ab6886e4/src/callback.jl#L37 and now PyCall doesn't work on Julia master.

**Comment by stevengj** [comment]
Thanks, should be fixed now.
