### ISSUE TITLE
recent changes to propertynames spits out key error

### ISSUE THREAD

**Issue by ppalmes** [JuliaPy/PyCall.jl#893]
- this happens when you call `propertynames` in `sklearn` to check for `fit or transform vs predict`. once you call one them, it throws a `key error` exception because while `propertynames` say `fit` or `transform/predict` is available, actually calling one of them breaks. `getmember` is a more stable call instead of `dir` which list methods which may not be callable.

**Comment by ppalmes** [comment]
https://github.com/IBM/Lale.jl/runs/2329281498?check_suite_focus=true

**Comment by stevengj** [comment]
cc @sethaxen since #879 is at issue here.

**Comment by ppalmes** [comment]
yes. i have to copy the old code which uses getmember so that my fit/transform call to sklearn works. i’m not sure why python returns key error. it seems the dir command has bogus return of fit/transform such that calling python object returns error because it doesn’t support it.

**Comment by sethaxen** [comment]
Could you provide a minimal example of a Python class for which `dir` fails but `getmember` works? See for example the [test class](https://github.com/JuliaPy/PyCall.jl/blob/8a98fb45ef39d09e11c1270e9120a32df2578d50/test/runtests.jl#L298-L300) added in #879 for which `dir` works but `getmember` fails.
