### ISSUE TITLE
print function in python not works called by julia through PyCall

### ISSUE THREAD

**Issue by ywlds** [JuliaPy/PyCall.jl#912]
The print function inside a python function when called by a julia function through PyCall seems not "print" anything at all?
How can I fixed it, so that when used Julia and Python, we can debug more interactively?

**Comment by stevengj** [comment]
Works for me:
```jl
julia> PyCall.py"print(\"Hello world\")"
Hello world
```
Are you running in a different environment, like a Jupyter notebook?  You may have a problem from the fact that Python's stdio streams are not the same as Julia's, so they might not be captured by the notebook.

**Comment by marcpabst** [comment]
I can confirm that this does not work in a Jupyter notebook. Any workarounds?

**Comment by stevengj** [comment]
It's just buffering.    `pyimport("sys").stdout.flush()` causes the output to appear in Jupyter.

**Comment by stevengj** [comment]
We can do this automatically with
```jl
if isdefined(Main, :IJulia) && IJulia.inited
    Main.IJulia.push_postexecute_hook(() -> pyimport("sys").stdout.flush())
end
```
Maybe we should do this in PyCall's `__init__` function?

**Comment by marcpabst** [comment]
Great, thanks!
