### ISSUE TITLE
PyCall & Anaconda terms of service

### ISSUE THREAD

**Issue by tverho** [JuliaPy/PyCall.jl#913]
Recently, Anaconda has changed the terms of service of its repository so that a commercial license is required in large organizations:

https://www.anaconda.com/terms-of-service
https://www.anaconda.com/blog/anaconda-commercial-edition-faq

Because PyCall often automatically opts to use an internal Conda installation that uses Anaconda repositories, that can easily lead to an unintentional breach of the ToS if the user is in a large organization. I think PyCall should not make such a choice without informing the user about the possible requirement of a commercial license.

A simple fix would be to disable the Anaconda repository and use Conda-forge instead. That way, the Anaconda ToS would not apply. Personally I find the easiest way to be to use Miniforge instead of Miniconda.

**Comment by DilumAluthge** [comment]
See also:
- https://github.com/JuliaPy/Conda.jl/issues/195
- https://github.com/JuliaPy/Conda.jl/issues/196

**Comment by stevengj** [comment]
Yes, it would be good to make this the default.

**Comment by stevengj** [comment]
Closed by #207.
