### ISSUE TITLE
Use local PyCall instead of global PyCall

### ISSUE THREAD

**Issue by KwatME** [JuliaPy/PyCall.jl#923]
I have a python program that uses PyCall. I'm installing PyCall globally. But I want to use local PyCall if possible. How do I make it happen? Ideally, I want to have a this Julia environment used by the program to be all contained by the program, instead of polluting the global Julia environment.

Thank you in advance,
Kwat

**Comment by stevengj** [comment]
Using the https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_DEPOT_PATH environment variable you can tell Julia to install packages into a private directory, separate from the regular Julia package installation.
