### ISSUE TITLE
A better type for docstring

### ISSUE THREAD

**Issue by melonedo** [JuliaPy/PyCall.jl#949]
https://github.com/JuliaPy/PyCall.jl/blob/e3e3008ee1b3e449c6382293f58a1f85384beea6/src/PyCall.jl#L260-L268
Docstring for python objects have the type `Base.Docs.Text{String}`, which has been deprecated. Since python documentation is usually in RST format, maybe we could create a type for that?

This has caused [trouble](https://github.com/fonsp/Pluto.jl/issues/1727) in Pluto when displaying documentation in the help panel.

**Comment by stevengj** [comment]
Since when is it deprecated?

If it's a `Text` type, it seems like a bug in Pluto to display it as markdown, since
```jl
julia> showable("text/markdown", Docs.Text("foo"))
false
```

**Comment by melonedo** [comment]
https://github.com/JuliaLang/julia/commit/86639e1abae97a7f46e8daa9ec83466865c854f4
It is deprecated since 1.7.

**Comment by stevengj** [comment]
1. It might in theory be removed in Julia 2.x, but it will be maintained for all Julia 1.x releases.
2. We would just replace it with something exactly equivalent (a type that has a `show` method for `text/plain` but not for `text/markdown`), so why bother?
3. Regardless of what type we use, we will trigger the same Pluto bug if they are assuming everything is markdown.

**Comment by melonedo** [comment]
I think you are right, another type won't fix the issue about Pluto. Nevertheless it is better to avoid deprecated interfaces.

**Comment by stevengj** [comment]
Closing this as it's not an issue in Julia 1.x, and the only alternative would to be to re-implement `Docs.Text`.

**Comment by stevengj** [comment]
See also #43532.
