### ISSUE TITLE
 invalid escape sequence

### ISSUE THREAD

**Issue by PARODBE** [JuliaPy/PyCall.jl#961]
Hi,

I am new using Julia, It is my first day...and I am trying to install diffeqpy but firstly I have to install some packages and put the path of Julia in the correct way, for this reason, I am doing:

ENV["PYTHON"]="C:\\Users\\...\\python.exe"

But I obtain the error:
ERROR: syntax: invalid escape sequence                                                                                  Stacktrace:                                                                                                              [1] top-level scope                                                                                                       @ none:1          

Could you help me please? and sorry for a so stupid question....

Thanks

**Comment by stevengj** [comment]
Use `raw"C:\...\python.exe"` — otherwise Julia treats a `\` in a string as an escape sequence.

I would encourage you to ask this sort of general Julia question on https://discourse.julialang.org/
